import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'flex-start',
  },
  appSafe: {
    backgroundColor: '#fff',
  },
  appSafeDark: {
    backgroundColor: '#0b0b0f',
  },
  authModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    padding: 12,
    justifyContent: 'center',
  },
  authModalOverlayInner: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  authModalSheet: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    // Keep it feeling like a popup, not a full screen.
    // ScrollView inside will handle overflow on small screens.
    maxHeight: 640,
    minHeight: 360,
    borderRadius: 16,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  authModalSheetDark: {
    backgroundColor: '#14141a',
  },
  authModalTopRow: {
    paddingHorizontal: 12,
    paddingTop: 6,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  authModalTopRowDark: {
    backgroundColor: '#14141a',
  },
  authModalBody: {
    paddingHorizontal: 12,
  },
  authModalBodyContent: {
    paddingBottom: 18,
  },
  authModalCloseCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f2f2f7',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    // Give it a little breathing room from the top/right edge of the sheet.
    marginTop: 4,
  },
  authModalCloseCircleDark: {
    backgroundColor: '#1c1c22',
    borderColor: '#2a2a33',
  },
  authModalCloseX: {
    fontSize: 22,
    lineHeight: 22,
    fontWeight: '900',
    color: '#111',
    marginTop: -1,
  },
  authModalCloseXDark: {
    color: '#fff',
  },
  authModalTitle: {
    fontWeight: '900',
    fontSize: 16,
    color: '#111',
  },
  authModalTitleDark: {
    color: '#fff',
  },
  authBackLinkBtn: {
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 4,
    marginTop: 6,
  },
  authBackLinkText: {
    fontWeight: '800',
    color: '#111',
    textDecorationLine: 'none',
  },
  authBackLinkTextDark: {
    color: '#fff',
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  rightControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  themeToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e3e3e3',
  },
  themeToggleDark: {
    backgroundColor: '#14141a',
    borderColor: '#2a2a33',
  },
  // Web-only: avoid browser default teal/blue accent that can bleed into the native Switch implementation.
  webToggleTrack: {
    width: 44,
    height: 26,
    borderRadius: 999,
    padding: 2,
    backgroundColor: '#d1d1d6',
    justifyContent: 'center',
  },
  webToggleTrackOn: {
    // Match mobile: keep the track light; the "on" state is indicated by thumb position.
    backgroundColor: '#d1d1d6',
  },
  webToggleThumb: {
    width: 22,
    height: 22,
    borderRadius: 999,
    backgroundColor: '#ffffff',
    transform: [{ translateX: 0 }],
  },
  webToggleThumbOn: {
    backgroundColor: '#2a2a33',
    transform: [{ translateX: 18 }],
  },
  menuIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuIconBtnDark: {
    backgroundColor: '#2a2a33',
    borderColor: '#2a2a33',
    borderWidth: 0,
  },
  segment: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f2f2f7',
    padding: 3,
    borderRadius: 12,
    gap: 4,
  },
  segmentDark: {
    backgroundColor: '#1c1c22',
  },
  segmentBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    minWidth: 84,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentBtnActive: {
    backgroundColor: '#fff',
  },
  segmentBtnActiveDark: {
    backgroundColor: '#2a2a33',
  },
  segmentBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#666',
  },
  segmentBtnTextDark: {
    color: '#b7b7c2',
  },
  segmentBtnTextActive: {
    color: '#111',
  },
  segmentBtnTextActiveDark: {
    color: '#fff',
  },
  dmPillInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#1976d2',
  },
  unreadChip: {
    minWidth: 26,
    height: 22,
    paddingHorizontal: 8,
    borderRadius: 999,
    backgroundColor: '#1976d2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  unreadChipDark: {
    backgroundColor: '#1976d2',
  },
  unreadChipText: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 12,
    lineHeight: 14,
  },
  unreadChipTextDark: {
    color: '#fff',
  },
  signOutPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e3e3e3',
  },
  signOutPillDark: {
    backgroundColor: '#14141a',
    borderColor: '#2a2a33',
  },
  signOutPillText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111',
  },
  signOutPillTextDark: {
    color: '#fff',
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 0,
    gap: 8,
    zIndex: 1,
  },
  searchWrapper: {
    marginTop: 6,
    marginBottom: 0,
  },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
    paddingHorizontal: 10,
    // Keep compact, but make sure text/placeholder are vertically centered (esp. Android).
    height: 36,
    paddingVertical: 0,
    textAlignVertical: 'center',
    // Light mode: make the entry field white.
    backgroundColor: '#fff',
    color: '#111',
    fontSize: 13,
    lineHeight: 16,
  },
  searchInputDark: {
    backgroundColor: '#14141a',
    borderColor: '#2a2a33',
    color: '#fff',
  },
  startDmBtn: {
    minHeight: 36,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#ddd',
  },
  startDmBtnDark: {
    backgroundColor: '#2a2a33',
    borderColor: '#2a2a33',
  },
  startDmBtnText: {
    color: '#111',
    fontWeight: '700',
    fontSize: 13,
    lineHeight: 16,
  },
  startDmBtnTextDark: {
    color: '#fff',
  },
  cancelBtn: {
    minHeight: 36,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#ddd',
    backgroundColor: '#fff',
  },
  cancelBtnDark: {
    backgroundColor: '#2a2a33',
    borderColor: '#2a2a33',
  },
  cancelBtnText: {
    color: '#111',
    fontWeight: '700',
    fontSize: 13,
    lineHeight: 16,
  },
  cancelBtnTextDark: {
    color: '#fff',
  },
  unreadList: {
    paddingHorizontal: 4,
    paddingTop: 4,
  },
  unreadHintWrapper: {
    paddingVertical: 0,
  },
  unreadHint: {
    color: '#555',
    fontSize: 13,
    marginTop: 0,
    paddingHorizontal: 4,
  },
  unreadHintDark: {
    color: '#b7b7c2',
  },
  unreadHintBold: {
    fontWeight: '700',
    // Keep unread sender highlight neutral in light mode (avoid bright blue).
    color: '#111',
  },
  unreadHintBoldDark: {
    color: '#fff',
  },
  errorText: {
    color: '#b00020',
    marginBottom: 8,
  },
  errorTextDark: {
    color: '#ff6b6b',
  },
  appContent: {
    flex: 1,
    alignSelf: 'stretch',
    position: 'relative',
  },
  appContentDark: {
    backgroundColor: '#0b0b0f',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    // Keep generic modals (alerts, recovery passphrase, etc.) reasonably sized on desktop web,
    // while preserving the refined native sizing.
    ...(Platform.OS === 'web'
      ? ({ width: '92%', maxWidth: 520, alignSelf: 'center' } as const)
      : ({ width: '80%' } as const)),
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 12,
    elevation: 6,
    position: 'relative',
  },
  modalContentDark: {
    backgroundColor: '#1c1c22',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
  },
  modalTitleDark: {
    color: '#fff',
  },
  modalHelperText: {
    color: '#555',
    marginBottom: 12,
    lineHeight: 18,
  },
  modalHelperTextDark: {
    color: '#b7b7c2',
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginBottom: 12,
  },
  passphraseFieldWrapper: {
    position: 'relative',
    width: '100%',
    marginBottom: 12,
  },
  passphraseInput: {
    paddingRight: 40, // room for the eye icon (match sign-in tighter inset)
    marginBottom: 0,
  },
  passphraseEyeBtn: {
    position: 'absolute',
    right: 8,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    width: 32,
  },
  passphraseErrorText: {
    color: '#b00020',
    marginTop: -4,
    marginBottom: 12,
    fontWeight: '700',
  },
  passphraseErrorTextDark: {
    color: '#ff6b6b',
  },
  modalInputLight: {
    color: '#111',
    backgroundColor: '#fff',
  },
  modalInputDark: {
    borderColor: '#2a2a33',
    backgroundColor: '#14141a',
    color: '#fff',
  },
  modalInputDisabled: {
    backgroundColor: '#f5f5f5',
    color: '#999',
  },
  modalInputDisabledDark: {
    backgroundColor: '#14141a',
    color: '#8f8fa3',
    opacity: 0.7,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  modalButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    // Light mode: neutral buttons should be off-gray (modal backgrounds are white).
    backgroundColor: '#f2f2f7',
    borderWidth: 1,
    // Neutral "tool button" style (avoid blue default buttons in light mode).
    borderColor: '#e3e3e3',
    // Web: avoid browser default focus ring tint (can appear green/blue on some platforms).
    ...(Platform.OS === 'web' ? { outlineStyle: 'none', boxShadow: 'none' } : null),
  },
  modalButtonSmall: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  modalButtonDark: {
    backgroundColor: '#2a2a33',
    borderColor: 'transparent',
    borderWidth: 0,
  },
  // Primary button for generic in-app alerts/confirmations (avoid bright blue; match app theme).
  modalButtonPrimary: {
    backgroundColor: '#111',
    borderColor: 'transparent',
  },
  modalButtonPrimaryDark: {
    backgroundColor: '#2a2a33',
    borderColor: 'transparent',
  },
  // CTA button for our in-app prompts (avoid bright blue in light mode).
  modalButtonCta: {
    backgroundColor: '#111',
    borderColor: 'transparent',
  },
  modalButtonCtaDark: {
    backgroundColor: '#2a2a33',
    borderColor: 'transparent',
  },
  modalButtonDanger: {
    backgroundColor: '#b00020',
    borderColor: 'transparent',
  },
  modalButtonDangerDark: {
    backgroundColor: '#ff6b6b',
    borderColor: 'transparent',
  },
  modalButtonText: {
    color: '#111',
    fontWeight: '800',
    textAlign: 'center',
  },
  modalButtonTextDark: {
    color: '#fff',
  },
  modalButtonPrimaryText: {
    color: '#fff',
  },
  modalButtonCtaText: {
    color: '#fff',
  },
  recoveryActionList: {
    marginTop: 12,
    gap: 10,
    alignSelf: 'stretch',
  },
  modalButtonDangerText: {
    color: '#fff',
  },
  chatsCard: {
    width: '92%',
    maxWidth: 520,
    // Modals should be white in light mode.
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    maxHeight: '70%',
    // Ensure the card sits above the modal backdrop Pressable for touch handling on Android.
    position: 'relative',
    zIndex: 2,
    elevation: 8,
  },
  chatsCardDark: {
    backgroundColor: '#14141a',
    borderColor: '#2a2a33',
  },
  profileCard: {
    width: '92%',
    maxWidth: 520,
    // Modals should be white in light mode.
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    maxHeight: '70%',
    // Ensure the card sits above the modal backdrop Pressable for touch handling on Android.
    position: 'relative',
    zIndex: 2,
    elevation: 8,
  },
  profileCardDark: { backgroundColor: '#14141a', borderColor: '#2a2a33' },
  profilePreviewRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 6 },
  profilePreviewMeta: { flex: 1 },
  bgPreviewBox: {
    width: 72,
    height: 54,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#fff',
  },
  bgPreviewImage: { width: '100%', height: '100%' },
  profileSectionTitle: { marginTop: 10, marginBottom: 6, fontWeight: '900' },
  avatarPaletteRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 4 },
  avatarColorDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(0,0,0,0.25)',
  },
  avatarColorDotSelected: { borderWidth: 2, borderColor: '#111', transform: [{ scale: 1.05 }] },
  avatarColorDotSelectedDark: { borderWidth: 2, borderColor: '#fff', transform: [{ scale: 1.05 }] },
  avatarTextColorRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  avatarTextColorBtn: {
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarTextColorBtnDark: { backgroundColor: '#1c1c22', borderColor: '#2a2a33' },
  avatarTextColorBtnSelected: { borderWidth: 2, borderColor: '#111' },
  avatarTextColorBtnSelectedDark: { borderWidth: 2, borderColor: '#fff' },
  avatarTextColorLabel: { fontWeight: '800', color: '#111' },
  avatarTextColorLabelDark: { color: '#fff' },
  profileActionsRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 12 },
  toolBtn: {
    flex: 1,
    height: 40,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolBtnDark: { backgroundColor: '#1c1c22', borderColor: '#2a2a33' },
  toolBtnText: { fontWeight: '800', color: '#111' },
  toolBtnTextDark: { color: '#fff' },
  bgEffectsHeaderRow: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', gap: 10, marginTop: 10 },
  bgEffectsResetBtn: { paddingHorizontal: 6, paddingVertical: 4 },
  bgEffectsResetText: { fontWeight: '900', color: '#111', opacity: 0.7 },
  bgEffectsResetTextDark: { fontWeight: '900', color: '#fff', opacity: 0.75 },
  // Keep sliders comfortably narrow (about ~2/3 modal width).
  bgSliderSection: { marginTop: 10, alignSelf: 'center', width: '64%', maxWidth: 320 },
  bgSliderLabelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, marginBottom: 4 },
  bgSliderLabel: { fontWeight: '900', color: '#111' },
  bgSliderLabelDark: { color: '#fff' },
  bgSliderValue: { fontWeight: '900', color: '#111', opacity: 0.75 },
  bgSliderValueDark: { color: '#fff', opacity: 0.8 },
  bgSlider: { width: '100%', height: 34, marginLeft: 4, marginRight: 4 },
  chatsTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  chatsCloseBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
  },
  chatsCloseBtnDark: { backgroundColor: '#2a2a33', borderWidth: 0, borderColor: 'transparent' },
  chatsCloseText: { color: '#111', fontWeight: '800' },
  chatsCloseTextDark: { color: '#fff' },
  chatsScroll: { maxHeight: 420, marginTop: 8 },
  chatsLoadingRow: { flexDirection: 'row', alignItems: 'baseline', gap: 4, paddingVertical: 6, paddingHorizontal: 2 },
  chatsLoadingText: { lineHeight: 18 },
  chatsLoadingDotsWrap: { marginBottom: 1 },
  chatRow: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  chatRowDark: { backgroundColor: '#1c1c22', borderColor: '#2a2a33' },
  chatRowLeft: { flexDirection: 'row', alignItems: 'center', gap: 8, flexGrow: 1, flexShrink: 1, minWidth: 0 },
  chatRowRight: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  chatRowName: { fontWeight: '800', color: '#111', flexGrow: 1, flexShrink: 1, minWidth: 0 },
  chatRowNameDark: { color: '#fff' },
  chatRowDate: { fontWeight: '800', fontSize: 13, color: '#111' },
  chatRowDateDark: { color: '#fff' },
  chatRowCount: { fontWeight: '900', color: '#1976d2' },
  chatRowCountDark: { color: '#fff' },
  memberChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#fff',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    minWidth: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  memberChipDark: { backgroundColor: '#2a2a33', borderColor: 'transparent' },
  memberChipText: { fontWeight: '900', color: '#111' },
  memberChipTextDark: { color: '#fff' },
  leaveChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#ffebee',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#ffcdd2',
  },
  leaveChipDark: { backgroundColor: '#2a2a33', borderColor: 'transparent' },
  leaveChipText: { color: '#c62828', fontWeight: '900' },
  leaveChipTextDark: { color: '#ff6b6b' },
  defaultChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
  },
  defaultChipDark: { backgroundColor: '#2a2a33', borderColor: 'transparent' },
  defaultChipText: { color: '#666', fontWeight: '900' },
  defaultChipTextDark: { color: '#a7a7b4' },
  chatDeleteBtn: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatDeleteBtnDark: { backgroundColor: '#2a2a33', borderWidth: 0, borderColor: 'transparent' },

  blocksCard: {
    width: '92%',
    maxWidth: 520,
    // Modals should be white in light mode.
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    maxHeight: '70%',
    // Ensure the card sits above the modal backdrop Pressable for touch handling on Android.
    position: 'relative',
    zIndex: 2,
    elevation: 8,
  },
  blocksCardDark: { backgroundColor: '#14141a', borderColor: '#2a2a33' },
  blocksTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  blocksSearchRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 8, marginBottom: 10 },
  blocksInput: {
    flex: 1,
    height: 40,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    backgroundColor: '#f2f2f7',
    paddingHorizontal: 12,
    color: '#111',
  },
  blocksInputDark: { backgroundColor: '#1c1c22', borderColor: '#2a2a33', color: '#fff' },
  blocksBtn: {
    height: 40,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  blocksBtnDark: { backgroundColor: '#2a2a33', borderColor: 'transparent' },
  blocksBtnText: { color: '#111', fontWeight: '800' },
  blocksBtnTextDark: { color: '#fff' },
  blocksScroll: { maxHeight: 420, marginTop: 2 },
  blockRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    marginBottom: 8,
  },
  blockRowDark: { backgroundColor: '#1c1c22', borderColor: '#2a2a33' },
  blockRowName: { fontWeight: '800', color: '#111', flexShrink: 1 },
  blockRowNameDark: { color: '#fff' },
  blockActionBtn: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  blockActionBtnDark: { backgroundColor: '#2a2a33', borderWidth: 0, borderColor: 'transparent' },
});

export type AppStyles = typeof styles;
