import Constants from 'expo-constants';
import { Platform } from 'react-native';

type Extra = {
  ORKA_ENV?: string;
  WS_URL?: string;
  API_URL?: string;
  AI_API_URL?: string;
  CDN_URL?: string;
  SIGNER_API_URL?: string;
};

// Support both new expoConfig.extra and legacy manifest extra
type LegacyConstantsWithManifestExtra = { manifestExtra?: unknown };
const legacy = Constants as LegacyConstantsWithManifestExtra;
const extra = (Constants.expoConfig?.extra ?? legacy.manifestExtra ?? {}) as Extra;

export const WS_URL: string = extra.WS_URL || '';
export const API_URL: string = extra.API_URL || '';
// Optional: point AI routes at a different base URL (e.g. REST API streaming or Lambda Function URL).
export const AI_API_URL: string = extra.AI_API_URL || '';
export const ORKA_ENV: string = extra.ORKA_ENV || 'production';

// Prefer Amplify outputs (generated by ampx) but allow Expo extra overrides.
let outputsCdnUrl = '';
let outputsSignerApiUrl = '';
try {
  // Use RN Platform instead of `navigator` so this works during web bundling in CI.
  const isWeb = Platform.OS === 'web';
  const isStaging =
    ORKA_ENV === 'staging' ||
    (typeof extra.API_URL === 'string' && extra.API_URL.includes('/staging')) ||
    (typeof extra.WS_URL === 'string' && extra.WS_URL.includes('/staging'));
  let outputs: any;
  if (isWeb) {
    outputs = isStaging
      ? require('../../amplify_outputs.web.staging.json')
      : require('../../amplify_outputs.web.json');
  } else {
    outputs = require('../../amplify_outputs.json');
  }
  outputsCdnUrl =
    typeof outputs?.custom?.cdnUrl === 'string'
      ? outputs.custom.cdnUrl
      : typeof outputs?.custom?.cdn_url === 'string'
        ? outputs.custom.cdn_url
        : '';
  outputsSignerApiUrl =
    typeof outputs?.custom?.signerApiUrl === 'string'
      ? outputs.custom.signerApiUrl
      : typeof outputs?.custom?.signer_api_url === 'string'
        ? outputs.custom.signer_api_url
        : '';
} catch {
  // ignore: amplify_outputs.json may not exist in early dev
}

export const CDN_URL: string = extra.CDN_URL || outputsCdnUrl || '';
export const SIGNER_API_URL: string = extra.SIGNER_API_URL || outputsSignerApiUrl || '';
