import { Platform, StyleSheet } from 'react-native';

import { APP_COLORS, APP_THEME_COLORS, PALETTE, withAlpha } from '../theme/colors';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: withAlpha(PALETTE.black, 0.5),
    justifyContent: 'center',
    alignItems: 'center',
  },
  safe: { flex: 1, backgroundColor: APP_THEME_COLORS.light.appBackground },
  safeDark: { backgroundColor: APP_THEME_COLORS.dark.appBackground },
  container: { flex: 1 },
  chatContentColumn: { width: '100%', maxWidth: 1040, alignSelf: 'center' },
  chatBody: { flex: 1, position: 'relative' },
  chatBodyInner: { flex: 1 },
  chatBgBase: { ...StyleSheet.absoluteFillObject },
  messageList: { flex: 1 },
  header: {
    paddingHorizontal: 16,
    paddingTop: 10,
    // Keep the bottom tight so the message list starts closer to the header content.
    paddingBottom: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: APP_COLORS.light.border.subtle,
    backgroundColor: APP_COLORS.light.bg.header,
  },
  headerDark: {
    backgroundColor: APP_COLORS.dark.bg.header,
    borderBottomColor: APP_COLORS.dark.border.subtle,
  },
  headerTopSlot: {
    // Small, consistent breathing room between the app-level headerTop controls
    // (Global/DM switch, menu, DM search) and the chat title row.
    marginBottom: 6,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    color: APP_COLORS.light.text.heading,
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  titleDark: { color: APP_COLORS.dark.text.primary },
  welcomeText: {
    fontSize: 14,
    color: APP_COLORS.light.text.secondary,
    marginTop: 2,
    fontWeight: '700',
  },
  welcomeTextDark: { color: APP_COLORS.dark.text.secondary },
  welcomeTextFlex: { flexGrow: 1, flexShrink: 1, minWidth: 0 },
  welcomeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  welcomeAvatar: { marginTop: 2, marginRight: 8, flexShrink: 0 },
  welcomeStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
    flexShrink: 0,
  },
  welcomeStatusText: { fontSize: 12, color: APP_COLORS.light.text.muted, fontWeight: '800' },
  headerSubRow: {
    marginTop: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  // (legacy) statusRow/statusText were used when connection status lived below the welcome line.
  statusRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 6 },
  statusText: { fontSize: 12, color: APP_COLORS.light.text.muted, marginTop: 6 },
  statusTextDark: { color: APP_COLORS.dark.text.muted },
  decryptRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  decryptLabel: { fontSize: 12, color: APP_COLORS.light.text.secondary, fontWeight: '600' },
  decryptLabelDark: { color: APP_COLORS.dark.text.secondary },
  dmHeaderControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
    flexShrink: 0,
    flexWrap: 'wrap',
  },
  dmHeaderControl: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dmSettingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 0,
    // Keep DM settings on a single horizontal line (no stacking).
    flexWrap: 'nowrap',
  },
  groupSettingsRow: {
    marginTop: 0,
  },
  dmSettingSlotLeft: { flex: 1, alignItems: 'flex-start', minWidth: 0 },
  dmSettingSlotCenter: { flex: 1, alignItems: 'center', minWidth: 0 },
  dmSettingSlotRight: { flex: 1, alignItems: 'flex-end', minWidth: 0 },
  dmSettingGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
    minWidth: 0,
  },
  channelAdminPanel: {
    // Two-row admin layout for channels (Members/Name/Leave, then Visibility/Password).
    alignSelf: 'stretch',
    flexDirection: 'column',
    marginTop: 0,
  },
  channelAdminRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  channelAdminActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    // Avoid relying on `gap` (not supported in some RN versions).
    marginLeft: 10,
  },
  dmSettingLabel: { flexShrink: 1, minWidth: 0 },
  dmSettingLabelCompact: { fontSize: 11 },
  ttlChipCompact: { paddingHorizontal: 8, paddingVertical: 4 },
  // Keep layout tight; use hitSlop on Pressable for tap area.
  dmSettingsCaretBtn: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniToggleTrack: {
    width: 28,
    height: 18,
    borderRadius: 999,
    backgroundColor: PALETTE.slate210,
    padding: 2,
    justifyContent: 'center',
  },
  miniToggleTrackDark: { backgroundColor: PALETTE.slate700 },
  // Theme-neutral: match light/dark UI (no blue/green accent).
  // Light: ON = slightly darker neutral gray. Dark: ON = white.
  miniToggleTrackOn: { backgroundColor: PALETTE.slate230 },
  miniToggleTrackOnDark: { backgroundColor: PALETTE.white },
  miniToggleThumb: {
    width: 14,
    height: 14,
    borderRadius: 999,
    backgroundColor: PALETTE.white,
    transform: [{ translateX: 0 }],
  },
  // In dark mode, use a dark thumb so it stays visible on the white "ON" track.
  miniToggleThumbDark: { backgroundColor: PALETTE.orkaDarkBg },
  miniToggleThumbOn: { transform: [{ translateX: 10 }] },
  miniToggleDisabled: { opacity: 0.6 },
  miniTogglePressed: { opacity: 0.85 },
  ttlChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: PALETTE.paper200,
  },
  ttlChipText: { fontSize: 12, color: PALETTE.slate870, fontWeight: '700' },
  ttlChipDark: {
    backgroundColor: PALETTE.slate750,
  },
  ttlChipTextDark: {
    color: PALETTE.white,
  },
  ttlOptionRow: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    backgroundColor: PALETTE.paper220,
  },
  ttlOptionRowSelected: { backgroundColor: APP_COLORS.light.text.primary },
  ttlOptionRowDark: {
    backgroundColor: APP_COLORS.dark.bg.header,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: APP_COLORS.dark.border.subtle,
  },
  ttlOptionRowSelectedDark: {
    backgroundColor: PALETTE.slate750,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PALETTE.slate700,
  },
  ttlOptionLabel: { color: APP_COLORS.light.text.heading, fontWeight: '600' },
  ttlOptionLabelSelected: { color: PALETTE.white, fontWeight: '800' },
  ttlOptionRadio: { color: APP_COLORS.light.text.heading, fontSize: 18, fontWeight: '800' },
  ttlOptionRadioSelected: { color: PALETTE.white },
  ttlOptionLabelDark: { color: PALETTE.white },
  summarizeBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: PALETTE.white,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PALETTE.lineMedium,
  },
  summarizeBtnDark: {
    backgroundColor: PALETTE.slate750,
    borderWidth: 0,
    borderColor: 'transparent',
  },
  summarizeBtnText: { color: APP_COLORS.light.text.primary, fontWeight: '700', fontSize: 13 },
  summarizeBtnTextDark: { color: PALETTE.white },
  headerTools: { flexDirection: 'row', alignItems: 'center', gap: 8, flexShrink: 1 },
  // kept for other modals using the same visual language
  toolBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    // Light mode: neutral modal buttons should be off-gray.
    backgroundColor: APP_COLORS.light.bg.surface2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: APP_COLORS.light.border.subtle,
  },
  toolBtnDark: {
    backgroundColor: PALETTE.slate750,
    borderWidth: 0,
    borderColor: 'transparent',
  },
  toolBtnText: { color: APP_COLORS.light.text.primary, fontWeight: '700', fontSize: 13 },
  toolBtnTextDark: { color: PALETTE.white },
  attachOptionBtn: {
    minHeight: 52,
    paddingVertical: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  attachOptionText: {
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '800',
  },
  ok: { color: PALETTE.successText },
  err: { color: APP_COLORS.light.status.errorText },
  error: { color: APP_COLORS.light.status.errorText, marginTop: 6 },
  errorDark: { color: APP_COLORS.dark.status.errorText },
  listContent: { paddingVertical: 12, paddingHorizontal: 6 },
  messageRow: {
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'flex-start',
    // On web, ensure the row measures full width so bubble maxWidth percentages behave as expected.
    width: '100%',
  },
  messageRowIncoming: { justifyContent: 'flex-start' },
  messageRowOutgoing: { justifyContent: 'flex-end' },
  avatarGutter: { marginRight: 8 },
  avatarSpacer: { opacity: 0 },
  messageBubble: {
    // Match guest screen behavior: allow bubbles to grow wider so long text wraps naturally.
    maxWidth: '96%',
    flexShrink: 1,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
  },
  // Media thumbnails should be allowed to be much wider (like typical chat apps),
  // while keeping text-only bubbles tighter.
  // (legacy) media bubble styles removed in favor of mediaCard layout
  messageBubbleIncoming: { backgroundColor: PALETTE.paper210 },
  messageBubbleIncomingDark: { backgroundColor: APP_COLORS.dark.bg.header },
  messageBubbleOutgoing: { backgroundColor: APP_COLORS.light.brand.primary },
  // Ensure inline-edit controls (Save/Cancel) have comfortable space and don't look clipped.
  messageBubbleEditing: { maxWidth: '96%', width: '96%', paddingBottom: 12 },
  // Retry hint needs to be readable on both light surfaces and the outgoing blue bubble.
  sendFailedText: { marginTop: 6, fontSize: 12, color: PALETTE.dangerRedDark, fontStyle: 'italic' },
  sendFailedTextDark: { color: APP_COLORS.dark.status.errorText },
  sendFailedTextAlignOutgoing: {
    textAlign: 'right',
    alignSelf: 'flex-end',
    // Use an OPAQUE red pill so it stays red on the blue bubble (no purple blending),
    // and white bold text for maximum contrast.
    backgroundColor: APP_COLORS.light.status.errorText,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    overflow: 'hidden',
    color: PALETTE.white,
    fontWeight: '700',
  },
  messageTextRow: { flexDirection: 'row', alignItems: 'flex-end' },
  messageTextRowOutgoing: { justifyContent: 'flex-end' },
  // minWidth:0 is important on web flexbox so long unbroken text (e.g. links) can shrink/wrap inside the bubble.
  messageTextFlex: { flexGrow: 1, flexShrink: 1, minWidth: 0 },
  mentionText: { fontWeight: '900' },
  replySnippet: {
    marginTop: 6,
    marginBottom: 6,
    paddingLeft: 10,
    borderLeftWidth: 2,
  },
  replySnippetOutgoing: { borderLeftColor: withAlpha(PALETTE.white, 0.75) },
  replySnippetIncoming: { borderLeftColor: withAlpha(PALETTE.black, 0.35) },
  replySnippetIncomingDark: { borderLeftColor: withAlpha(PALETTE.white, 0.35) },
  replySnippetLabel: { fontSize: 12, fontWeight: '900' },
  replySnippetLabelOutgoing: { color: withAlpha(PALETTE.white, 0.92) },
  replySnippetLabelIncoming: { color: APP_COLORS.light.text.secondary },
  replySnippetLabelIncomingDark: { color: APP_COLORS.dark.text.muted },
  replySnippetText: { fontSize: 13, marginTop: 2 },
  replySnippetTextOutgoing: { color: withAlpha(PALETTE.white, 0.92) },
  replySnippetTextIncoming: { color: APP_COLORS.light.text.primary },
  replySnippetTextIncomingDark: { color: APP_COLORS.dark.text.primary },
  replyThumbWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 6,
    alignSelf: 'flex-start',
  },
  replyThumb: { width: '100%', height: '100%' },
  replyThumbPlaceholder: {
    backgroundColor: withAlpha(PALETTE.black, 0.12),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  replyThumbPlaceholderText: {
    fontSize: 9,
    fontWeight: '900',
    color: withAlpha(PALETTE.black, 0.55),
    textAlign: 'center',
  },
  replyThumbCountBadge: {
    position: 'absolute',
    right: 2,
    bottom: 2,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: withAlpha(PALETTE.black, 0.65),
  },
  replyThumbCountText: { color: APP_COLORS.dark.text.primary, fontSize: 10, fontWeight: '900' },
  sendStatusInline: { marginLeft: 6, fontSize: 12 },
  sendStatusInlineOutgoing: { color: withAlpha(PALETTE.white, 0.9) }, // readable on blue bubble (light mode)
  sendStatusInlineOutgoingDark: { color: withAlpha(PALETTE.white, 0.85) }, // readable on blue bubble (dark mode)
  sendStatusInlineIncoming: { color: APP_COLORS.light.text.secondary }, // readable on light bubble
  sendStatusInlineIncomingDark: { color: APP_COLORS.dark.text.muted }, // readable on dark bubble

  editedLabel: { marginLeft: 6, fontSize: 12, fontStyle: 'italic', fontWeight: '400' },
  editedLabelOutgoing: { color: withAlpha(PALETTE.white, 0.9) },
  editedLabelOutgoingDark: { color: withAlpha(PALETTE.white, 0.85) },
  editedLabelIncoming: { color: APP_COLORS.light.text.secondary },
  editedLabelIncomingDark: { color: APP_COLORS.dark.text.muted },
  deletedText: { fontStyle: 'italic', opacity: 0.9 },
  inlineEditWrap: { flex: 1, width: '100%' },
  inlineEditInput: {
    fontSize: 16,
    paddingVertical: 0,
    paddingHorizontal: 0,
    marginTop: 1,
    fontWeight: '400',
    backgroundColor: 'transparent',
    // Web: prevent the browser's default <textarea> border/outline (can look like a double line).
    ...(Platform.OS === 'web'
      ? ({
          borderWidth: 0,
          outlineStyle: 'solid',
          outlineWidth: 0,
          outlineColor: 'transparent',
          boxShadow: 'none',
        } as const)
      : null),
  },
  inlineEditInputIncoming: { color: APP_COLORS.light.text.heading },
  // Outgoing edits sit on the blue bubble/header bar → a single white border reads best in both light/dark themes.
  inlineEditInputOutgoing: {
    color: APP_COLORS.dark.text.primary,
    borderWidth: 1,
    // Default (unfocused): subtle border so it doesn't look "stuck focused".
    borderColor: withAlpha(PALETTE.white, 0.45),
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  inlineEditInputOutgoingFocused: {
    borderColor: withAlpha(PALETTE.white, 0.92),
    // Make the focus ring 1px thicker, but keep overall size stable.
    borderWidth: 2,
    paddingHorizontal: 7,
    paddingVertical: 5,
  },
  inlineEditActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 8,
    width: '100%',
  },
  inlineEditBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: withAlpha(PALETTE.black, 0.08),
  },
  inlineEditBtnPressed: { opacity: 0.75 },
  // When editing an outgoing media message, the editor sits on a blue header bar.
  // Use a translucent white pill so "Uploading…" doesn't look like a disabled grey block.
  inlineEditBtnUploadingOutgoing: {
    backgroundColor: withAlpha(PALETTE.white, 0.18),
    borderColor: 'transparent',
    opacity: 0.95,
  },
  inlineEditBtnText: { fontWeight: '700' },
  inlineEditBtnTextIncoming: { color: APP_COLORS.light.text.primary },
  inlineEditBtnTextOutgoing: { color: APP_COLORS.dark.text.primary },
  mediaEditHint: { marginTop: 6, fontSize: 12, fontWeight: '700' },
  mediaEditHintIncoming: { color: APP_COLORS.light.text.secondary },
  mediaEditHintIncomingDark: { color: APP_COLORS.dark.text.secondary },
  mediaEditHintOutgoing: { color: withAlpha(PALETTE.white, 0.85) },
  messageMeta: { fontSize: 12, marginBottom: 1, fontWeight: '700' },
  messageMetaIncoming: { color: APP_COLORS.light.text.secondary },
  messageMetaIncomingDark: { color: APP_COLORS.dark.text.secondary },
  messageMetaOutgoing: { color: withAlpha(PALETTE.white, 0.9), textAlign: 'right' },
  messageText: { fontSize: 16, marginTop: 1, fontWeight: '400' },
  messageTextIncoming: { color: APP_COLORS.light.text.heading },
  messageTextIncomingDark: { color: APP_COLORS.dark.text.primary },
  messageTextOutgoing: { color: APP_COLORS.dark.text.primary },
  attachmentLink: {
    marginTop: 6,
    fontSize: 13,
    color: APP_COLORS.light.brand.primary,
    fontWeight: '400',
    textDecorationLine: 'underline',
  },
  mediaAlignIncoming: { alignSelf: 'flex-start' },
  mediaAlignOutgoing: { alignSelf: 'flex-end' },
  imagePreview: {
    marginTop: 8,
    width: '100%',
    borderRadius: 16,
    backgroundColor: PALETTE.paper250,
  },
  imageThumbWrap: {
    width: '100%',
    height: 220,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    overflow: 'hidden',
    // For resizeMode="contain", let the parent `mediaCard` provide the background.
    // This avoids a visible dark seam between the header and the media in light mode.
    backgroundColor: 'transparent',
  },
  mediaAutoImage: {
    width: '100%',
    backgroundColor: 'transparent',
  },
  mediaCappedImage: {
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    // Let the parent provide letterbox background.
    backgroundColor: 'transparent',
  },
  mediaFrame: {
    marginTop: 8,
    width: '100%',
    borderRadius: 16,
    overflow: 'hidden',
    // Match the message bubble background so "contain" letterboxing doesn't show as white.
    backgroundColor: PALETTE.black,
  },
  mediaFill: {
    width: '100%',
    height: '100%',
    backgroundColor: 'transparent',
  },
  mediaThumb: {
    width: '100%',
    height: 220,
    backgroundColor: PALETTE.black,
  },
  imageFrame: {
    // Prefer showing the entire image (no cropping). Slightly shorter so tall images don't dominate.
    height: 180,
  },
  videoThumbWrap: {
    width: '100%',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    overflow: 'hidden',
    backgroundColor: PALETTE.black,
  },
  mediaMsg: {
    width: '96%',
  },
  mediaMsgIncoming: { alignItems: 'flex-start' },
  mediaMsgOutgoing: { alignItems: 'flex-end' },
  mediaCard: {
    width: '100%',
    borderRadius: 16,
    overflow: 'hidden',
  },
  // Outer wrapper to allow reaction chips to float outside the clipped (rounded) card.
  mediaCardOuter: { position: 'relative', overflow: 'visible' },
  mediaCardIncoming: { backgroundColor: PALETTE.paper210 },
  mediaCardIncomingDark: { backgroundColor: APP_COLORS.dark.bg.header },
  // Outgoing image thumbs use "contain" → use a neutral letterbox background (not brand-blue).
  mediaCardOutgoing: { backgroundColor: PALETTE.slate900 },
  mediaHeader: {
    paddingHorizontal: 12,
    paddingTop: 6,
    paddingBottom: 4,
  },
  mediaHeaderIncoming: { backgroundColor: PALETTE.paper210 },
  mediaHeaderIncomingDark: { backgroundColor: APP_COLORS.dark.bg.header },
  mediaHeaderOutgoing: { backgroundColor: APP_COLORS.light.brand.primary },
  mediaHeaderMeta: { fontSize: 12, fontWeight: '700' },
  mediaHeaderMetaIncoming: { color: APP_COLORS.light.text.secondary },
  mediaHeaderMetaIncomingDark: { color: APP_COLORS.dark.text.secondary },
  mediaHeaderMetaOutgoing: { color: withAlpha(PALETTE.white, 0.9), textAlign: 'right' },
  mediaHeaderCaption: { marginTop: 4, fontSize: 16, fontWeight: '400' },
  mediaHeaderCaptionIncoming: { color: APP_COLORS.light.text.heading },
  mediaHeaderCaptionIncomingDark: { color: APP_COLORS.dark.text.primary },
  mediaHeaderCaptionOutgoing: { color: APP_COLORS.dark.text.primary },
  videoPlayOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoPlayText: {
    color: APP_COLORS.dark.text.primary,
    fontSize: 42,
    fontWeight: '900',
    ...(Platform.OS === 'web'
      ? { textShadow: `0px 2px 6px ${withAlpha(PALETTE.black, 0.6)}` }
      : {
          textShadowColor: withAlpha(PALETTE.black, 0.6),
          textShadowOffset: { width: 0, height: 2 },
          textShadowRadius: 6,
        }),
  },
  extraThumbRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 10,
    gap: 8,
  },
  extraThumb: {
    width: 56,
    height: 56,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: withAlpha(PALETTE.black, 0.08),
  },
  extraThumbMediaWrap: { width: '100%', height: '100%' },
  extraThumbImage: { width: '100%', height: '100%' },
  extraThumbPlayOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  extraThumbPlayText: {
    color: APP_COLORS.dark.text.primary,
    fontSize: 18,
    fontWeight: '900',
    ...(Platform.OS === 'web'
      ? { textShadow: `0px 1px 4px ${withAlpha(PALETTE.black, 0.7)}` }
      : {
          textShadowColor: withAlpha(PALETTE.black, 0.7),
          textShadowOffset: { width: 0, height: 1 },
          textShadowRadius: 4,
        }),
  },
  extraThumbPlaceholder: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  extraThumbPlaceholderText: { fontSize: 12, fontWeight: '800', color: APP_COLORS.light.text.body },
  mediaCountBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: withAlpha(PALETTE.black, 0.55),
    zIndex: 5,
  },
  mediaCountBadgeText: { color: APP_COLORS.dark.text.primary, fontWeight: '900', fontSize: 12 },
  mediaCarouselNavBtn: {
    position: 'absolute',
    top: '50%',
    marginTop: -18,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: withAlpha(PALETTE.black, 0.35),
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: withAlpha(PALETTE.white, 0.18),
    zIndex: 7,
  },
  mediaCarouselNavLeft: { left: 10 },
  mediaCarouselNavRight: { right: 10 },
  mediaCarouselNavText: {
    color: APP_COLORS.dark.text.primary,
    fontWeight: '900',
    fontSize: 22,
    lineHeight: 22,
    marginTop: -1,
  },
  mediaDotsOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 6,
  },
  mediaDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: withAlpha(PALETTE.black, 0.28),
  },
  mediaDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: withAlpha(PALETTE.white, 0.55),
  },
  mediaDotActive: {
    width: 16,
    backgroundColor: withAlpha(PALETTE.white, 0.95),
  },
  seenText: {
    marginTop: 6,
    fontSize: 12,
    fontStyle: 'italic',
    fontWeight: '600',
  },
  seenTextAlignIncoming: { alignSelf: 'flex-start', textAlign: 'left' },
  seenTextAlignOutgoing: { alignSelf: 'flex-end', textAlign: 'right' },
  seenTextIncoming: { color: APP_COLORS.light.brand.primary },
  seenTextOutgoing: { color: withAlpha(PALETTE.white, 0.9) },
  // For outgoing MEDIA messages the seen label is rendered on the screen background (not inside the blue bubble),
  // so use a readable light-mode color.
  seenTextOutgoingOnLightSurface: { color: APP_COLORS.light.brand.primary },
  inputRow: {
    width: '100%',
    alignSelf: 'stretch',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: APP_COLORS.light.border.subtle,
    backgroundColor: APP_COLORS.light.bg.surface2,
  },
  inputRowInner: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    width: '100%',
    paddingTop: 8,
    paddingBottom: 8,
  },
  inputRowDark: {
    backgroundColor: APP_COLORS.dark.bg.header,
    borderTopColor: APP_COLORS.dark.border.default,
  },
  attachmentPill: {
    marginHorizontal: 12,
    marginBottom: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: APP_COLORS.light.bg.surface2,
    borderWidth: 1,
    borderColor: APP_COLORS.light.border.subtle,
  },
  attachmentPillText: { color: APP_COLORS.light.text.primary, fontWeight: '700' },
  attachmentPillDark: {
    backgroundColor: APP_COLORS.dark.bg.header,
    borderColor: APP_COLORS.dark.border.default,
  },
  attachmentPillTextDark: { color: APP_COLORS.dark.text.primary },
  pickBtn: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: APP_COLORS.light.bg.app,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PALETTE.lineMedium,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  pickBtnDark: {
    backgroundColor: PALETTE.slate750,
    borderWidth: 0,
    borderColor: 'transparent',
  },
  pickTxt: {
    color: APP_COLORS.light.text.primary,
    fontWeight: '800',
    fontSize: 18,
    lineHeight: 18,
  },
  pickTxtDark: { color: APP_COLORS.dark.text.primary },
  input: {
    flex: 1,
    flexBasis: 0,
    minWidth: 0,
    height: 44,
    // Explicit text metrics + vertical alignment to prevent clipping on iOS/Android.
    fontSize: 15,
    // Use a lineHeight matching the control height for stable vertical centering.
    lineHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 0,
    ...(Platform.OS === 'android'
      ? ({
          textAlignVertical: 'center',
          includeFontPadding: false,
        } as const)
      : {}),
    borderWidth: 1,
    borderColor: PALETTE.lineMedium,
    borderRadius: 8,
    backgroundColor: APP_COLORS.light.bg.app,
    color: APP_COLORS.light.text.primary,
  },
  inputDark: {
    backgroundColor: APP_COLORS.dark.bg.surface,
    borderColor: APP_COLORS.dark.border.default,
    color: APP_COLORS.dark.text.primary,
  },
  typingRow: {
    paddingHorizontal: 12,
    paddingBottom: 6,
  },
  // (editingBar styles removed; save/cancel now live inside the edited message bubble)
  typingIndicatorRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  typingDotsRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingLeft: 2,
  },
  typingText: {
    fontSize: 14,
    color: APP_COLORS.light.text.muted,
    fontWeight: '600',
    fontStyle: 'italic',
  },
  typingTextDark: {
    color: APP_COLORS.dark.text.muted,
  },
  typingDot: {
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 18,
  },
  sendBtn: {
    marginLeft: 8,
    height: 44,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: APP_COLORS.light.bg.app,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PALETTE.lineMedium,
  },
  sendBtnDark: {
    backgroundColor: PALETTE.slate750,
    borderWidth: 0,
    borderColor: 'transparent',
  },
  sendBtnUploading: {
    backgroundColor: APP_COLORS.light.text.primary,
    borderColor: APP_COLORS.light.text.primary,
    opacity: 0.92,
  },
  sendBtnUploadingDark: {
    backgroundColor: PALETTE.slate750,
    borderWidth: 0,
    borderColor: 'transparent',
    opacity: 0.8,
  },
  sendTxt: { color: APP_COLORS.light.text.primary, fontWeight: '700' },
  sendTxtDark: { color: APP_COLORS.dark.text.primary },
  btnDisabled: {
    backgroundColor: APP_COLORS.light.bg.surface2,
    borderColor: PALETTE.lineMedium,
    opacity: 0.8,
  },
  btnDisabledDark: {
    backgroundColor: PALETTE.slate650,
    borderWidth: 0,
    borderColor: 'transparent',
    opacity: 0.6,
  },
  reportPreviewBox: {
    marginTop: 12,
    marginBottom: 10,
    borderRadius: 12,
    padding: 10,
    minHeight: 72,
    backgroundColor: PALETTE.nearWhite,
    borderWidth: 1,
    borderColor: PALETTE.fog,
  },
  reportPreviewBoxDark: {
    backgroundColor: APP_COLORS.dark.bg.header,
    borderColor: APP_COLORS.dark.border.default,
  },
  reportPreviewLabel: { fontWeight: '800', color: APP_COLORS.light.text.primary, marginBottom: 4 },
  reportPreviewLabelDark: { color: APP_COLORS.dark.text.primary },
  reportPreviewText: { color: APP_COLORS.light.text.heading, lineHeight: 18 },
  reportPreviewTextDark: { color: APP_COLORS.dark.text.body },
  reportTargetLine: {
    marginTop: 10,
    marginBottom: 6,
    color: APP_COLORS.light.text.heading,
    fontWeight: '700',
  },
  reportTargetLineDark: { color: APP_COLORS.dark.text.body },
  reportNoticeBox: {
    marginTop: 10,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  reportNoticeBoxDark: {},
  reportNoticeBoxError: {
    backgroundColor: PALETTE.dangerBgLight,
    borderColor: PALETTE.dangerBorderLight,
  },
  reportNoticeBoxErrorDark: {
    backgroundColor: PALETTE.dangerBgDark,
    borderColor: PALETTE.dangerBorderDark,
  },
  reportNoticeBoxSuccess: {
    backgroundColor: PALETTE.successBg,
    borderColor: PALETTE.successBgStrong,
  },
  reportNoticeBoxSuccessDark: {
    backgroundColor: PALETTE.successBgDark,
    borderColor: PALETTE.successTextDark,
  },
  reportNoticeText: { fontWeight: '800', lineHeight: 18 },
  reportNoticeTextDark: {},
  reportNoticeTextError: { color: APP_COLORS.light.status.errorText },
  reportNoticeTextErrorDark: { color: PALETTE.dangerPink },
  reportNoticeTextSuccess: { color: PALETTE.successBorder },
  reportNoticeTextSuccessDark: { color: PALETTE.successGreen },
  reportInput: {
    marginTop: 10,
    minHeight: 96,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: PALETTE.fog,
    // Off-color so it stands out from the modal background.
    backgroundColor: APP_COLORS.light.bg.surface2,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: APP_COLORS.light.text.primary,
    textAlignVertical: 'top',
    ...(Platform.OS === 'web'
      ? ({
          // Avoid the browser default focus outline (can clip in ScrollViews and doesn't match our rounded inputs).
          // Use a "zero-width solid" outline so it stays type-safe across RN-web style typings.
          outlineStyle: 'solid',
          outlineWidth: 0,
          outlineColor: 'transparent',
        } as const)
      : null),
  },
  reportInputDark: {
    borderColor: APP_COLORS.dark.border.default,
    backgroundColor: APP_COLORS.dark.bg.header,
    color: APP_COLORS.dark.text.primary,
  },
  reportInputFocused: {
    // Match other web inputs: solid black focus ring (but inset so it won't clip in modals).
    ...(Platform.OS === 'web'
      ? ({
          boxShadow: `inset 0px 0px 0px 1px ${PALETTE.black}`,
        } as const)
      : null),
  },
  reportInputFocusedDark: {
    // Match other web inputs: thicker white focus ring in dark mode (inset to avoid clipping).
    ...(Platform.OS === 'web'
      ? ({
          boxShadow: `inset 0px 0px 0px 2px ${PALETTE.white}`,
        } as const)
      : null),
  },
  reportCategoryWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  reportChip: {
    borderWidth: 1,
    borderColor: PALETTE.fog,
    backgroundColor: APP_COLORS.light.bg.app,
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  reportChipDark: {
    borderColor: APP_COLORS.dark.border.default,
    backgroundColor: APP_COLORS.dark.bg.header,
  },
  // Keep chips neutral; "Report" should look destructive, not brand-blue.
  reportChipActive: {
    borderColor: APP_COLORS.light.text.primary,
    backgroundColor: APP_COLORS.light.bg.surface2,
  },
  reportChipActiveDark: {
    borderColor: APP_COLORS.dark.text.primary,
    backgroundColor: PALETTE.slate750,
  },
  reportChipText: { color: APP_COLORS.light.text.heading, fontWeight: '800' },
  reportChipTextDark: { color: APP_COLORS.dark.text.body },
  reportChipTextActive: { color: APP_COLORS.light.text.primary },
  reportChipTextActiveDark: { color: APP_COLORS.dark.text.primary },
  reportTargetSwitchWrap: { flexDirection: 'row', gap: 10, marginTop: 10, alignItems: 'center' },
  reportTargetToggleLabel: { color: APP_COLORS.light.text.heading, fontWeight: '900' },
  reportTargetToggleLabelDark: { color: APP_COLORS.dark.text.body },
  reportTargetChip: {
    borderWidth: 1,
    borderColor: PALETTE.fog,
    backgroundColor: APP_COLORS.light.bg.app,
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  reportTargetChipDark: {
    borderColor: APP_COLORS.dark.border.default,
    backgroundColor: APP_COLORS.dark.bg.header,
  },
  reportTargetChipActive: {
    borderColor: APP_COLORS.light.text.primary,
    backgroundColor: APP_COLORS.light.bg.surface2,
  },
  reportTargetChipActiveDark: {
    borderColor: APP_COLORS.dark.text.primary,
    backgroundColor: PALETTE.slate750,
  },
  reportTargetChipText: { color: APP_COLORS.light.text.heading, fontWeight: '900' },
  reportTargetChipTextDark: { color: APP_COLORS.dark.text.body },
  reportTargetChipTextActive: { color: APP_COLORS.light.text.primary },
  reportBtnDanger: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: APP_COLORS.light.status.errorText,
    borderWidth: 0,
  },
  reportBtnDangerDark: { backgroundColor: PALETTE.dangerPink },
  reportBtnDangerText: { color: APP_COLORS.dark.text.primary, fontWeight: '800', fontSize: 13 },
  summaryModal: {
    // On desktop web, constrain width/height so it feels like a modal (not a giant sheet).
    ...(Platform.OS === 'web'
      ? ({ width: '92%', maxWidth: 720, maxHeight: 640, alignSelf: 'center' } as const)
      : ({ width: '88%', maxHeight: '80%' } as const)),
    minHeight: 0,
    // Modals should be white in light mode.
    backgroundColor: APP_COLORS.light.bg.app,
    borderRadius: 12,
    padding: 16,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 10,
    color: APP_COLORS.light.text.primary,
  },
  summaryLoadingRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 8 },
  summaryLoadingText: { color: APP_COLORS.light.text.secondary, fontWeight: '600' },
  // IMPORTANT: allow scroll areas inside modals to shrink on small screens
  // so footer buttons (Done/Close/Cancel) remain reachable.
  summaryScroll: {
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
    ...(Platform.OS === 'web' ? ({ width: '100%', alignSelf: 'stretch' } as const) : null),
  },
  summaryText: { color: APP_COLORS.light.text.heading, lineHeight: 20 },
  summaryButtons: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 12, gap: 10 },
  summaryModalDark: { backgroundColor: APP_COLORS.dark.bg.surface },
  summaryTitleDark: { color: APP_COLORS.dark.text.primary },
  summaryTextDark: { color: APP_COLORS.dark.text.body },
  helperInput: {
    minHeight: 44,
    maxHeight: 140,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PALETTE.lineMedium,
    backgroundColor: APP_COLORS.light.bg.header,
    color: APP_COLORS.light.text.primary,
    ...(Platform.OS === 'web' ? ({ width: '100%', alignSelf: 'stretch' } as const) : null),
  },
  helperInputFollowUp: {
    marginTop: 10,
  },
  helperInputDark: {
    borderColor: APP_COLORS.dark.border.default,
    backgroundColor: APP_COLORS.dark.bg.header,
    color: APP_COLORS.dark.text.primary,
  },
  helperModeRow: { marginTop: 8 },
  helperModeSegment: {
    flexDirection: 'row',
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: PALETTE.mist,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PALETTE.lineMedium,
  },
  helperModeSegmentDark: {
    backgroundColor: APP_COLORS.dark.bg.header,
    borderColor: APP_COLORS.dark.border.default,
  },
  helperModeBtn: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  helperModeBtnActive: {
    backgroundColor: APP_COLORS.light.text.primary,
  },
  helperModeBtnActiveDark: {
    backgroundColor: APP_COLORS.light.bg.app,
  },
  helperModeBtnText: { fontWeight: '800', color: APP_COLORS.light.text.primary },
  helperModeBtnTextDark: { color: APP_COLORS.dark.text.primary },
  helperModeBtnTextActive: { color: APP_COLORS.dark.text.primary },
  helperModeBtnTextActiveDark: { color: APP_COLORS.light.text.primary },
  helperHint: { marginTop: 8, fontSize: 12, color: APP_COLORS.light.text.muted, fontWeight: '600' },
  helperHintDark: { color: APP_COLORS.dark.text.muted },
  helperBlock: { marginTop: 10 },
  helperSectionTitle: {
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 6,
    color: APP_COLORS.light.text.primary,
  },
  helperTurnBubble: {
    borderRadius: 12,
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PALETTE.paper270,
  },
  helperTurnBubbleUser: {
    backgroundColor: PALETTE.paper230,
  },
  helperTurnBubbleAssistant: {
    backgroundColor: PALETTE.paper240,
  },
  helperTurnBubbleDark: {
    borderColor: APP_COLORS.dark.border.default,
  },
  helperTurnBubbleUserDark: {
    backgroundColor: APP_COLORS.dark.bg.header,
  },
  helperTurnBubbleAssistantDark: {
    backgroundColor: APP_COLORS.dark.bg.surface,
  },
  helperTurnLabel: {
    fontSize: 12,
    fontWeight: '800',
    opacity: 0.8,
    marginBottom: 6,
  },
  helperSuggestionBubble: {
    borderRadius: 12,
    padding: 12,
    backgroundColor: PALETTE.paper220,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: PALETTE.paper280,
  },
  helperSuggestionBubbleDark: {
    backgroundColor: APP_COLORS.dark.bg.header,
    borderColor: APP_COLORS.dark.border.default,
  },
  helperSuggestionText: { color: APP_COLORS.light.text.heading, lineHeight: 20 },
  helperSuggestionActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 10,
  },
  actionMenuOverlay: { flex: 1, backgroundColor: withAlpha(PALETTE.black, 0.35) },
  actionMenuCard: {
    backgroundColor: APP_COLORS.light.bg.app,
    borderRadius: 14,
    overflow: 'hidden',
    ...(Platform.OS === 'web'
      ? { boxShadow: `0px 10px 18px ${withAlpha(PALETTE.black, 0.22)}` }
      : {
          shadowColor: PALETTE.black,
          shadowOpacity: 0.22,
          shadowRadius: 18,
          shadowOffset: { width: 0, height: 10 },
        }),
    elevation: 12,
  },
  actionMenuCardDark: { backgroundColor: APP_COLORS.dark.bg.surface },
  actionMenuPreviewRow: { padding: 14, borderBottomWidth: 1, borderBottomColor: PALETTE.paper200 },
  actionMenuPreviewRowDark: { borderBottomColor: APP_COLORS.dark.border.default },
  actionMenuMediaPreview: { gap: 10 },
  actionMenuMediaThumbWrap: { alignSelf: 'flex-start' },
  actionMenuMediaThumb: { width: 96, height: 96, borderRadius: 12 },
  actionMenuMediaThumbPlaceholder: {
    width: 96,
    height: 96,
    borderRadius: 12,
    backgroundColor: PALETTE.mist,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionMenuMediaThumbPlaceholderText: {
    color: APP_COLORS.light.text.secondary,
    fontWeight: '700',
  },
  actionMenuMediaMeta: {
    color: APP_COLORS.light.text.muted,
    fontWeight: '700',
    fontSize: 12,
    marginTop: -4,
  },
  actionMenuMediaMetaDark: { color: APP_COLORS.dark.text.muted },
  actionMenuMediaCaption: { color: APP_COLORS.light.text.heading, lineHeight: 18 },
  actionMenuMediaCaptionDark: { color: APP_COLORS.dark.text.body },
  actionMenuOptions: { paddingVertical: 6 },
  actionMenuOptionsScroll: {
    flexGrow: 0,
    flexShrink: 1,
    minHeight: 0,
  },
  actionMenuOptionsContent: { paddingVertical: 6 },
  reactionInfoRow: { flexDirection: 'row', alignItems: 'baseline', flexWrap: 'wrap' },
  reactionInfoRemoveHint: {
    opacity: 0.75,
    fontSize: 12,
    fontWeight: '700',
    fontStyle: 'italic',
    marginLeft: 8,
  },
  reactionOverlay: {
    position: 'absolute',
    bottom: -12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0,
  },
  // Always anchor reaction chips to the right edge (incoming + outgoing),
  // so they line up consistently with the sender-side layout.
  reactionOverlayIncoming: { right: 10 },
  reactionOverlayOutgoing: { right: 10, flexDirection: 'row-reverse' },
  mediaHeaderTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  mediaHeaderTopLeft: { flex: 1, paddingRight: 10 },
  mediaHeaderTopRight: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end' },
  mediaHeaderCaptionRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  mediaHeaderCaptionFlex: { flex: 1, marginTop: 0 },
  mediaHeaderCaptionIndicators: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  reactionMiniChip: {
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 3,
    backgroundColor: APP_COLORS.light.bg.surface2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: APP_COLORS.light.border.subtle,
    ...(Platform.OS === 'web'
      ? { boxShadow: `0px 2px 6px ${withAlpha(PALETTE.black, 0.08)}` }
      : {
          shadowColor: PALETTE.black,
          shadowOpacity: 0.08,
          shadowRadius: 6,
          shadowOffset: { width: 0, height: 2 },
        }),
    elevation: 2,
  },
  // Keep reaction chips consistent: no overlapping/stacking.
  reactionMiniChipStacked: {
    marginLeft: 0,
  },
  reactionMiniChipDark: {
    backgroundColor: APP_COLORS.dark.bg.header,
    borderColor: APP_COLORS.dark.border.default,
    ...(Platform.OS === 'web' ? { boxShadow: 'none' } : { shadowOpacity: 0 }),
    elevation: 0,
  },
  reactionMiniChipMine: {
    // Higher-contrast "selected by me" in light theme
    backgroundColor: withAlpha(PALETTE.slate900, 0.18),
    borderColor: withAlpha(PALETTE.slate900, 0.65),
  },
  reactionMiniChipMineDark: {
    backgroundColor: withAlpha(PALETTE.brandBlue, 0.22),
    borderColor: withAlpha(PALETTE.brandBlue, 0.45),
  },
  reactionMiniText: { color: APP_COLORS.light.text.primary, fontWeight: '800', fontSize: 12 },
  reactionMiniTextDark: { color: APP_COLORS.dark.text.primary },
  reactionQuickRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingBottom: 10,
    paddingTop: 6,
    gap: 10,
  },
  reactionQuickScrollContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingRight: 6,
  },
  reactionQuickBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: APP_COLORS.light.bg.surface2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: APP_COLORS.light.border.subtle,
  },
  reactionQuickBtnDark: {
    backgroundColor: APP_COLORS.dark.bg.header,
    borderColor: APP_COLORS.dark.border.default,
  },
  reactionQuickBtnMine: {
    backgroundColor: withAlpha(PALETTE.slate900, 0.2),
    borderColor: withAlpha(PALETTE.slate900, 0.7),
  },
  reactionQuickBtnMineDark: {
    backgroundColor: withAlpha(PALETTE.brandBlue, 0.25),
    borderColor: withAlpha(PALETTE.brandBlue, 0.45),
  },
  reactionQuickEmoji: { fontSize: 18 },
  reactionQuickMore: {
    height: 38,
    paddingHorizontal: 12,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: APP_COLORS.light.bg.surface2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: APP_COLORS.light.border.subtle,
  },
  reactionQuickMoreDark: {
    backgroundColor: APP_COLORS.dark.bg.header,
    borderColor: APP_COLORS.dark.border.default,
  },
  reactionQuickMoreText: { color: APP_COLORS.light.text.primary, fontWeight: '800' },
  reactionQuickMoreTextDark: { color: APP_COLORS.dark.text.primary },
  reactionPickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingVertical: 10,
  },
  reactionPickerBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: APP_COLORS.light.bg.surface2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: APP_COLORS.light.border.subtle,
  },
  reactionPickerBtnDark: {
    backgroundColor: APP_COLORS.dark.bg.header,
    borderColor: APP_COLORS.dark.border.default,
  },
  reactionPickerBtnMine: {
    backgroundColor: withAlpha(PALETTE.slate900, 0.2),
    borderColor: withAlpha(PALETTE.slate900, 0.7),
  },
  reactionPickerBtnMineDark: {
    backgroundColor: withAlpha(PALETTE.brandBlue, 0.25),
    borderColor: withAlpha(PALETTE.brandBlue, 0.45),
  },
  reactionPickerEmoji: { fontSize: 20 },
  actionMenuRow: { paddingHorizontal: 16, paddingVertical: 12 },
  actionMenuRowPressed: { opacity: 0.75 },
  actionMenuText: { fontSize: 16, color: APP_COLORS.light.text.primary, fontWeight: '600' },
  actionMenuTextDark: { color: APP_COLORS.dark.text.primary },
  viewerOverlay: {
    flex: 1,
    backgroundColor: withAlpha(PALETTE.black, 0.85),
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  viewerCard: {
    width: '100%',
    height: '100%',
    borderRadius: 0,
    overflow: 'hidden',
    backgroundColor: PALETTE.black,
    position: 'relative',
  },
  viewerTopBar: {
    height: 52,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: withAlpha(PALETTE.black, 0.35),
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  viewerTitle: { color: APP_COLORS.dark.text.primary, fontWeight: '700', flex: 1, marginRight: 12 },
  viewerCloseBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: withAlpha(PALETTE.black, 0.35),
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: withAlpha(PALETTE.white, 0.18),
  },
  viewerCloseText: { color: APP_COLORS.dark.text.primary, fontWeight: '700' },
  viewerBody: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  viewerTapArea: { flex: 1, width: '100%', height: '100%' },
  viewerNavBtn: {
    position: 'absolute',
    top: '50%',
    marginTop: -24,
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: withAlpha(PALETTE.black, 0.35),
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: withAlpha(PALETTE.white, 0.18),
    zIndex: 11,
  },
  viewerNavLeft: { left: 12 },
  viewerNavRight: { right: 12 },
  viewerNavText: {
    color: APP_COLORS.dark.text.primary,
    fontWeight: '900',
    fontSize: 28,
    lineHeight: 28,
    marginTop: -2,
  },
  // RN-web deprecates `style.resizeMode`; use the Image prop instead.
  viewerImage: { width: '100%', height: '100%' },
  viewerVideo: { width: '100%', height: '100%' },
  viewerFallback: { color: APP_COLORS.dark.text.primary },
  toastWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toast: {
    maxWidth: 340,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: PALETTE.slate900,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: withAlpha(PALETTE.white, 0.12),
  },
  toastDark: {
    backgroundColor: APP_COLORS.dark.bg.header,
    borderColor: APP_COLORS.dark.border.default,
  },
  toastError: {
    backgroundColor: APP_COLORS.light.status.errorText,
    borderColor: withAlpha(PALETTE.white, 0.18),
  },
  toastErrorDark: {
    backgroundColor: PALETTE.dangerAccentDark,
    borderColor: withAlpha(PALETTE.white, 0.12),
  },
  toastText: {
    color: APP_COLORS.dark.text.primary,
    fontWeight: '800',
    fontSize: 13,
    textAlign: 'center',
  },
});

export type ChatScreenStyles = typeof styles;
