import { Platform, StyleSheet } from 'react-native';
import { APP_THEME_COLORS } from '../theme/colors';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  safe: { flex: 1, backgroundColor: APP_THEME_COLORS.light.appBackground },
  safeDark: { backgroundColor: APP_THEME_COLORS.dark.appBackground },
  container: { flex: 1 },
  chatContentColumn: { width: '100%', maxWidth: 1040, alignSelf: 'center' },
  chatBody: { flex: 1, position: 'relative' },
  chatBodyInner: { flex: 1 },
  chatBgBase: { ...StyleSheet.absoluteFillObject },
  messageList: { flex: 1 },
  header: {
    paddingHorizontal: 16,
    paddingTop: 10,
    // Keep the bottom tight so the message list starts closer to the header content.
    paddingBottom: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e3e3e3',
    backgroundColor: '#fafafa',
  },
  headerDark: {
    backgroundColor: '#1c1c22',
    borderBottomColor: '#2a2a33',
  },
  headerTopSlot: {
    // Small, consistent breathing room between the app-level headerTop controls
    // (Global/DM switch, menu, DM search) and the chat title row.
    marginBottom: 6,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  title: { fontSize: 20, fontWeight: '600', color: '#222', flexGrow: 1, flexShrink: 1, minWidth: 0 },
  titleDark: { color: '#fff' },
  welcomeText: { fontSize: 14, color: '#555', marginTop: 2, fontWeight: '700' },
  welcomeTextDark: { color: '#b7b7c2' },
  welcomeTextFlex: { flexGrow: 1, flexShrink: 1, minWidth: 0 },
  welcomeRow: { flexDirection: 'row', alignItems: 'center', flexGrow: 1, flexShrink: 1, minWidth: 0 },
  welcomeAvatar: { marginTop: 2, marginRight: 8, flexShrink: 0 },
  welcomeStatusRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 2, flexShrink: 0 },
  welcomeStatusText: { fontSize: 12, color: '#666', fontWeight: '800' },
  headerSubRow: {
    marginTop: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  // (legacy) statusRow/statusText were used when connection status lived below the welcome line.
  statusRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 6 },
  statusText: { fontSize: 12, color: '#666', marginTop: 6 },
  statusTextDark: { color: '#a7a7b4' },
  decryptRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 8 },
  decryptLabel: { fontSize: 12, color: '#555', fontWeight: '600' },
  decryptLabelDark: { color: '#b7b7c2' },
  dmHeaderControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
    flexShrink: 0,
    flexWrap: 'wrap',
  },
  dmHeaderControl: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dmSettingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 0,
    // Keep DM settings on a single horizontal line (no stacking).
    flexWrap: 'nowrap',
  },
  groupSettingsRow: {
    marginTop: 0,
  },
  dmSettingSlotLeft: { flex: 1, alignItems: 'flex-start', minWidth: 0 },
  dmSettingSlotCenter: { flex: 1, alignItems: 'center', minWidth: 0 },
  dmSettingSlotRight: { flex: 1, alignItems: 'flex-end', minWidth: 0 },
  dmSettingGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
    minWidth: 0,
  },
  channelAdminPanel: {
    // Two-row admin layout for channels (Members/Name/Leave, then Visibility/Password).
    alignSelf: 'stretch',
    flexDirection: 'column',
    marginTop: 0,
  },
  channelAdminRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  channelAdminActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    // Avoid relying on `gap` (not supported in some RN versions).
    marginLeft: 10,
  },
  dmSettingLabel: { flexShrink: 1, minWidth: 0 },
  dmSettingLabelCompact: { fontSize: 11 },
  ttlChipCompact: { paddingHorizontal: 8, paddingVertical: 4 },
  // Keep layout tight; use hitSlop on Pressable for tap area.
  dmSettingsCaretBtn: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniToggleTrack: {
    width: 28,
    height: 18,
    borderRadius: 999,
    backgroundColor: '#cfd2d8',
    padding: 2,
    justifyContent: 'center',
  },
  miniToggleTrackDark: { backgroundColor: '#3a3a46' },
  // Theme-neutral: match light/dark UI (no blue/green accent).
  // Light: ON = slightly darker neutral gray. Dark: ON = white.
  miniToggleTrackOn: { backgroundColor: '#aeb2bb' },
  miniToggleTrackOnDark: { backgroundColor: '#fff' },
  miniToggleThumb: {
    width: 14,
    height: 14,
    borderRadius: 999,
    backgroundColor: '#fff',
    transform: [{ translateX: 0 }],
  },
  // In dark mode, use a dark thumb so it stays visible on the white "ON" track.
  miniToggleThumbDark: { backgroundColor: '#0b0b0f' },
  miniToggleThumbOn: { transform: [{ translateX: 10 }] },
  miniToggleDisabled: { opacity: 0.6 },
  miniTogglePressed: { opacity: 0.85 },
  ttlChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#eee',
  },
  ttlChipText: { fontSize: 12, color: '#333', fontWeight: '700' },
  ttlChipDark: {
    backgroundColor: '#2a2a33',
  },
  ttlChipTextDark: {
    color: '#fff',
  },
  ttlOptionRow: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    backgroundColor: '#f4f4f4',
  },
  ttlOptionRowSelected: { backgroundColor: '#111' },
  ttlOptionRowDark: {
    backgroundColor: '#1c1c22',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#2a2a33',
  },
  ttlOptionRowSelectedDark: {
    backgroundColor: '#2a2a33',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#3a3a46',
  },
  ttlOptionLabel: { color: '#222', fontWeight: '600' },
  ttlOptionLabelSelected: { color: '#fff', fontWeight: '800' },
  ttlOptionRadio: { color: '#222', fontSize: 18, fontWeight: '800' },
  ttlOptionRadioSelected: { color: '#fff' },
  ttlOptionLabelDark: { color: '#fff' },
  summarizeBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#fff',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#ddd',
  },
  summarizeBtnDark: {
    backgroundColor: '#2a2a33',
    borderWidth: 0,
    borderColor: 'transparent',
  },
  summarizeBtnText: { color: '#111', fontWeight: '700', fontSize: 13 },
  summarizeBtnTextDark: { color: '#fff' },
  headerTools: { flexDirection: 'row', alignItems: 'center', gap: 8, flexShrink: 1 },
  // kept for other modals using the same visual language
  toolBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    // Light mode: neutral modal buttons should be off-gray.
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
  },
  toolBtnDark: {
    backgroundColor: '#2a2a33',
    borderWidth: 0,
    borderColor: 'transparent',
  },
  toolBtnText: { color: '#111', fontWeight: '700', fontSize: 13 },
  toolBtnTextDark: { color: '#fff' },
  attachOptionBtn: {
    minHeight: 52,
    paddingVertical: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  attachOptionText: {
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '800',
  },
  ok: { color: '#2e7d32' },
  err: { color: '#b00020' },
  error: { color: '#b00020', marginTop: 6 },
  errorDark: { color: '#ff6b6b' },
  listContent: { paddingVertical: 12, paddingHorizontal: 6 },
  messageRow: {
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'flex-start',
    // On web, ensure the row measures full width so bubble maxWidth percentages behave as expected.
    width: '100%',
  },
  messageRowIncoming: { justifyContent: 'flex-start' },
  messageRowOutgoing: { justifyContent: 'flex-end' },
  avatarGutter: { marginRight: 8 },
  avatarSpacer: { opacity: 0 },
  messageBubble: {
    // Match guest screen behavior: allow bubbles to grow wider so long text wraps naturally.
    maxWidth: '96%',
    flexShrink: 1,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
  },
  // Media thumbnails should be allowed to be much wider (like typical chat apps),
  // while keeping text-only bubbles tighter.
  // (legacy) media bubble styles removed in favor of mediaCard layout
  messageBubbleIncoming: { backgroundColor: '#f1f1f1' },
  messageBubbleIncomingDark: { backgroundColor: '#1c1c22' },
  messageBubbleOutgoing: { backgroundColor: '#1976d2' },
  messageBubbleEditing: { maxWidth: '96%', width: '96%' },
  // Retry hint needs to be readable on both light surfaces and the outgoing blue bubble.
  sendFailedText: { marginTop: 6, fontSize: 12, color: '#8b0000', fontStyle: 'italic' },
  sendFailedTextDark: { color: '#ff6b6b' },
  sendFailedTextAlignOutgoing: {
    textAlign: 'right',
    alignSelf: 'flex-end',
    // Use an OPAQUE red pill so it stays red on the blue bubble (no purple blending),
    // and white bold text for maximum contrast.
    backgroundColor: '#b00020',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    overflow: 'hidden',
    color: '#fff',
    fontWeight: '700',
  },
  messageTextRow: { flexDirection: 'row', alignItems: 'flex-end' },
  messageTextRowOutgoing: { justifyContent: 'flex-end' },
  // minWidth:0 is important on web flexbox so long unbroken text (e.g. links) can shrink/wrap inside the bubble.
  messageTextFlex: { flexGrow: 1, flexShrink: 1, minWidth: 0 },
  mentionText: { fontWeight: '900' },
  replySnippet: {
    marginTop: 6,
    marginBottom: 6,
    paddingLeft: 10,
    borderLeftWidth: 2,
  },
  replySnippetOutgoing: { borderLeftColor: 'rgba(255,255,255,0.75)' },
  replySnippetIncoming: { borderLeftColor: 'rgba(0,0,0,0.35)' },
  replySnippetIncomingDark: { borderLeftColor: 'rgba(255,255,255,0.35)' },
  replySnippetLabel: { fontSize: 12, fontWeight: '900' },
  replySnippetLabelOutgoing: { color: 'rgba(255,255,255,0.92)' },
  replySnippetLabelIncoming: { color: '#555' },
  replySnippetLabelIncomingDark: { color: '#a7a7b4' },
  replySnippetText: { fontSize: 13, marginTop: 2 },
  replySnippetTextOutgoing: { color: 'rgba(255,255,255,0.92)' },
  replySnippetTextIncoming: { color: '#111' },
  replySnippetTextIncomingDark: { color: '#fff' },
  replyThumbWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 6,
    alignSelf: 'flex-start',
  },
  replyThumb: { width: '100%', height: '100%' },
  replyThumbPlaceholder: {
    backgroundColor: 'rgba(0,0,0,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  replyThumbPlaceholderText: { fontSize: 9, fontWeight: '900', color: 'rgba(0,0,0,0.55)', textAlign: 'center' },
  replyThumbCountBadge: {
    position: 'absolute',
    right: 2,
    bottom: 2,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.65)',
  },
  replyThumbCountText: { color: '#fff', fontSize: 10, fontWeight: '900' },
  sendStatusInline: { marginLeft: 6, fontSize: 12 },
  sendStatusInlineOutgoing: { color: 'rgba(255,255,255,0.9)' }, // readable on blue bubble (light mode)
  sendStatusInlineOutgoingDark: { color: 'rgba(255,255,255,0.85)' }, // readable on blue bubble (dark mode)
  sendStatusInlineIncoming: { color: '#555' }, // readable on light bubble
  sendStatusInlineIncomingDark: { color: '#a7a7b4' }, // readable on dark bubble

  editedLabel: { marginLeft: 6, fontSize: 12, fontStyle: 'italic', fontWeight: '400' },
  editedLabelOutgoing: { color: 'rgba(255,255,255,0.9)' },
  editedLabelOutgoingDark: { color: 'rgba(255,255,255,0.85)' },
  editedLabelIncoming: { color: '#555' },
  editedLabelIncomingDark: { color: '#a7a7b4' },
  deletedText: { fontStyle: 'italic', opacity: 0.9 },
  inlineEditWrap: { flex: 1, width: '100%' },
  inlineEditInput: {
    fontSize: 16,
    paddingVertical: 0,
    paddingHorizontal: 0,
    marginTop: 1,
    fontWeight: '400',
  },
  inlineEditInputIncoming: { color: '#222' },
  inlineEditInputOutgoing: { color: '#fff' },
  inlineEditActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 8,
    width: '100%',
  },
  inlineEditBtn: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 10, backgroundColor: 'rgba(0,0,0,0.08)' },
  inlineEditBtnPressed: { opacity: 0.75 },
  // When editing an outgoing media message, the editor sits on a blue header bar.
  // Use a translucent white pill so "Uploading…" doesn't look like a disabled grey block.
  inlineEditBtnUploadingOutgoing: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderColor: 'transparent',
    opacity: 0.95,
  },
  inlineEditBtnText: { fontWeight: '700' },
  inlineEditBtnTextIncoming: { color: '#111' },
  inlineEditBtnTextOutgoing: { color: '#fff' },
  mediaEditHint: { marginTop: 6, fontSize: 12, fontWeight: '700' },
  mediaEditHintIncoming: { color: '#555' },
  mediaEditHintIncomingDark: { color: '#b7b7c2' },
  mediaEditHintOutgoing: { color: 'rgba(255,255,255,0.85)' },
  messageMeta: { fontSize: 12, marginBottom: 1, fontWeight: '700' },
  messageMetaIncoming: { color: '#555' },
  messageMetaIncomingDark: { color: '#b7b7c2' },
  messageMetaOutgoing: { color: 'rgba(255,255,255,0.9)', textAlign: 'right' },
  messageText: { fontSize: 16, marginTop: 1, fontWeight: '400' },
  messageTextIncoming: { color: '#222' },
  messageTextIncomingDark: { color: '#fff' },
  messageTextOutgoing: { color: '#fff' },
  attachmentLink: {
    marginTop: 6,
    fontSize: 13,
    color: '#1976d2',
    fontWeight: '400',
    textDecorationLine: 'underline',
  },
  mediaAlignIncoming: { alignSelf: 'flex-start' },
  mediaAlignOutgoing: { alignSelf: 'flex-end' },
  imagePreview: {
    marginTop: 8,
    width: '100%',
    borderRadius: 16,
    backgroundColor: '#e9e9e9',
  },
  imageThumbWrap: {
    width: '100%',
    height: 220,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    overflow: 'hidden',
    // For resizeMode="contain", let the parent `mediaCard` provide the background.
    // This avoids a visible dark seam between the header and the media in light mode.
    backgroundColor: 'transparent',
  },
  mediaAutoImage: {
    width: '100%',
    backgroundColor: 'transparent',
  },
  mediaCappedImage: {
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    // Let the parent provide letterbox background.
    backgroundColor: 'transparent',
  },
  mediaFrame: {
    marginTop: 8,
    width: '100%',
    borderRadius: 16,
    overflow: 'hidden',
    // Match the message bubble background so "contain" letterboxing doesn't show as white.
    backgroundColor: '#000',
  },
  mediaFill: {
    width: '100%',
    height: '100%',
    backgroundColor: 'transparent',
  },
  mediaThumb: {
    width: '100%',
    height: 220,
    backgroundColor: '#000',
  },
  imageFrame: {
    // Prefer showing the entire image (no cropping). Slightly shorter so tall images don't dominate.
    height: 180,
  },
  videoThumbWrap: {
    width: '100%',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#000',
  },
  mediaMsg: {
    width: '96%',
  },
  mediaMsgIncoming: { alignItems: 'flex-start' },
  mediaMsgOutgoing: { alignItems: 'flex-end' },
  mediaCard: {
    width: '100%',
    borderRadius: 16,
    overflow: 'hidden',
  },
  // Outer wrapper to allow reaction chips to float outside the clipped (rounded) card.
  mediaCardOuter: { position: 'relative', overflow: 'visible' },
  mediaCardIncoming: { backgroundColor: '#f1f1f1' },
  mediaCardIncomingDark: { backgroundColor: '#1c1c22' },
  // Outgoing media uses "contain" sometimes → match outgoing bubble background behind letterbox.
  mediaCardOutgoing: { backgroundColor: '#1976d2' },
  mediaHeader: {
    paddingHorizontal: 12,
    paddingTop: 6,
    paddingBottom: 4,
  },
  mediaHeaderIncoming: { backgroundColor: '#f1f1f1' },
  mediaHeaderIncomingDark: { backgroundColor: '#1c1c22' },
  mediaHeaderOutgoing: { backgroundColor: '#1976d2' },
  mediaHeaderMeta: { fontSize: 12, fontWeight: '700' },
  mediaHeaderMetaIncoming: { color: '#555' },
  mediaHeaderMetaIncomingDark: { color: '#b7b7c2' },
  mediaHeaderMetaOutgoing: { color: 'rgba(255,255,255,0.9)', textAlign: 'right' },
  mediaHeaderCaption: { marginTop: 4, fontSize: 16, fontWeight: '400' },
  mediaHeaderCaptionIncoming: { color: '#222' },
  mediaHeaderCaptionIncomingDark: { color: '#fff' },
  mediaHeaderCaptionOutgoing: { color: '#fff' },
  videoPlayOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoPlayText: {
    color: '#fff',
    fontSize: 42,
    fontWeight: '900',
    ...(Platform.OS === 'web'
      ? { textShadow: '0px 2px 6px rgba(0,0,0,0.6)' }
      : { textShadowColor: 'rgba(0,0,0,0.6)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 6 }),
  },
  extraThumbRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 10,
    gap: 8,
  },
  extraThumb: {
    width: 56,
    height: 56,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: 'rgba(0,0,0,0.08)',
  },
  extraThumbMediaWrap: { width: '100%', height: '100%' },
  extraThumbImage: { width: '100%', height: '100%' },
  extraThumbPlayOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  extraThumbPlayText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '900',
    ...(Platform.OS === 'web'
      ? { textShadow: '0px 1px 4px rgba(0,0,0,0.7)' }
      : { textShadowColor: 'rgba(0,0,0,0.7)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 4 }),
  },
  extraThumbPlaceholder: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  extraThumbPlaceholderText: { fontSize: 12, fontWeight: '800', color: '#444' },
  mediaCountBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.55)',
    zIndex: 5,
  },
  mediaCountBadgeText: { color: '#fff', fontWeight: '900', fontSize: 12 },
  mediaCarouselNavBtn: {
    position: 'absolute',
    top: '50%',
    marginTop: -18,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.18)',
    zIndex: 7,
  },
  mediaCarouselNavLeft: { left: 10 },
  mediaCarouselNavRight: { right: 10 },
  mediaCarouselNavText: { color: '#fff', fontWeight: '900', fontSize: 22, lineHeight: 22, marginTop: -1 },
  mediaDotsOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 6,
  },
  mediaDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.28)',
  },
  mediaDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.55)',
  },
  mediaDotActive: {
    width: 16,
    backgroundColor: 'rgba(255,255,255,0.95)',
  },
  seenText: {
    marginTop: 6,
    fontSize: 12,
    fontStyle: 'italic',
    fontWeight: '600',
  },
  seenTextAlignIncoming: { alignSelf: 'flex-start', textAlign: 'left' },
  seenTextAlignOutgoing: { alignSelf: 'flex-end', textAlign: 'right' },
  seenTextIncoming: { color: '#1976d2' },
  seenTextOutgoing: { color: 'rgba(255,255,255,0.9)' },
  // For outgoing MEDIA messages the seen label is rendered on the screen background (not inside the blue bubble),
  // so use a readable light-mode color.
  seenTextOutgoingOnLightSurface: { color: '#1976d2' },
  inputRow: {
    width: '100%',
    alignSelf: 'stretch',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#e3e3e3',
    backgroundColor: '#f2f2f7',
  },
  inputRowInner: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    width: '100%',
    paddingTop: 8,
    paddingBottom: 8,
  },
  inputRowDark: {
    backgroundColor: '#1c1c22',
    borderTopColor: '#2a2a33',
  },
  attachmentPill: {
    marginHorizontal: 12,
    marginBottom: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#f2f2f7',
    borderWidth: 1,
    borderColor: '#e3e3e3',
  },
  attachmentPillText: { color: '#111', fontWeight: '700' },
  attachmentPillDark: {
    backgroundColor: '#1c1c22',
    borderColor: '#2a2a33',
  },
  attachmentPillTextDark: { color: '#fff' },
  pickBtn: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: '#fff',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#ddd',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  pickBtnDark: {
    backgroundColor: '#2a2a33',
    borderWidth: 0,
    borderColor: 'transparent',
  },
  pickTxt: { color: '#111', fontWeight: '800', fontSize: 18, lineHeight: 18 },
  pickTxtDark: { color: '#fff' },
  input: {
    flex: 1,
    flexBasis: 0,
    minWidth: 0,
    height: 44,
    // Explicit text metrics + vertical alignment to prevent clipping on iOS/Android.
    fontSize: 15,
    // Use a lineHeight matching the control height for stable vertical centering.
    lineHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 0,
    ...(Platform.OS === 'android'
      ? ({
          textAlignVertical: 'center',
          includeFontPadding: false,
        } as const)
      : {}),
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    backgroundColor: '#fff',
    color: '#111',
  },
  inputDark: {
    backgroundColor: '#14141a',
    borderColor: '#2a2a33',
    color: '#fff',
  },
  typingRow: {
    paddingHorizontal: 12,
    paddingBottom: 6,
  },
  editingBar: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f2f2f7',
  },
  editingBarDark: { backgroundColor: '#1c1c22' },
  editingBarText: { color: '#444', fontWeight: '600' },
  editingBarTextDark: { color: '#d7d7e0' },
  editingBarCancelBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: '#e6e6ef',
  },
  editingBarCancelBtnDark: { backgroundColor: '#2a2a33' },
  editingBarCancelText: { color: '#111', fontWeight: '700' },
  editingBarCancelTextDark: { color: '#fff' },
  typingIndicatorRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  typingDotsRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingLeft: 2,
  },
  typingText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '600',
    fontStyle: 'italic',
  },
  typingTextDark: {
    color: '#a7a7b4',
  },
  typingDot: {
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 18,
  },
  sendBtn: {
    marginLeft: 8,
    height: 44,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#fff',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#ddd',
  },
  sendBtnDark: {
    backgroundColor: '#2a2a33',
    borderWidth: 0,
    borderColor: 'transparent',
  },
  sendBtnUploading: {
    backgroundColor: '#111',
    borderColor: '#111',
    opacity: 0.92,
  },
  sendBtnUploadingDark: {
    backgroundColor: '#2a2a33',
    borderWidth: 0,
    borderColor: 'transparent',
    opacity: 0.8,
  },
  sendTxt: { color: '#111', fontWeight: '700' },
  sendTxtDark: { color: '#fff' },
  btnDisabled: {
    backgroundColor: '#f2f2f7',
    borderColor: '#ddd',
    opacity: 0.8,
  },
  btnDisabledDark: {
    backgroundColor: '#444',
    borderWidth: 0,
    borderColor: 'transparent',
    opacity: 0.6,
  },
  reportPreviewBox: {
    marginTop: 12,
    marginBottom: 10,
    borderRadius: 12,
    padding: 10,
    minHeight: 72,
    backgroundColor: '#f6f6fb',
    borderWidth: 1,
    borderColor: '#e7e7ee',
  },
  reportPreviewBoxDark: { backgroundColor: '#1c1c22', borderColor: '#2a2a33' },
  reportPreviewLabel: { fontWeight: '800', color: '#111', marginBottom: 4 },
  reportPreviewLabelDark: { color: '#fff' },
  reportPreviewText: { color: '#222', lineHeight: 18 },
  reportPreviewTextDark: { color: '#d7d7e0' },
  reportTargetLine: { marginTop: 10, marginBottom: 6, color: '#222', fontWeight: '700' },
  reportTargetLineDark: { color: '#d7d7e0' },
  reportNoticeBox: {
    marginTop: 10,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  reportNoticeBoxDark: {},
  reportNoticeBoxError: { backgroundColor: '#fff5f5', borderColor: '#ffd5d5' },
  reportNoticeBoxErrorDark: { backgroundColor: '#2a1518', borderColor: '#5a2a2f' },
  reportNoticeBoxSuccess: { backgroundColor: '#f0fff4', borderColor: '#c7f0d0' },
  reportNoticeBoxSuccessDark: { backgroundColor: '#0f2317', borderColor: '#1f4d33' },
  reportNoticeText: { fontWeight: '800', lineHeight: 18 },
  reportNoticeTextDark: {},
  reportNoticeTextError: { color: '#b00020' },
  reportNoticeTextErrorDark: { color: '#cf6679' },
  reportNoticeTextSuccess: { color: '#0b6b2c' },
  reportNoticeTextSuccessDark: { color: '#7de6a5' },
  reportInput: {
    marginTop: 10,
    minHeight: 96,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e7e7ee',
    // Off-color so it stands out from the modal background.
    backgroundColor: '#f2f2f7',
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#111',
    textAlignVertical: 'top',
  },
  reportInputDark: {
    borderColor: '#2a2a33',
    backgroundColor: '#1c1c22',
    color: '#fff',
  },
  reportCategoryWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  reportChip: {
    borderWidth: 1,
    borderColor: '#e7e7ee',
    backgroundColor: '#fff',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  reportChipDark: { borderColor: '#2a2a33', backgroundColor: '#1c1c22' },
  // Keep chips neutral; "Report" should look destructive, not brand-blue.
  reportChipActive: { borderColor: '#111', backgroundColor: '#f2f2f7' },
  reportChipActiveDark: { borderColor: '#fff', backgroundColor: '#2a2a33' },
  reportChipText: { color: '#222', fontWeight: '800' },
  reportChipTextDark: { color: '#d7d7e0' },
  reportChipTextActive: { color: '#111' },
  reportChipTextActiveDark: { color: '#fff' },
  reportTargetSwitchWrap: { flexDirection: 'row', gap: 10, marginTop: 10, alignItems: 'center' },
  reportTargetToggleLabel: { color: '#222', fontWeight: '900' },
  reportTargetToggleLabelDark: { color: '#d7d7e0' },
  reportTargetChip: {
    borderWidth: 1,
    borderColor: '#e7e7ee',
    backgroundColor: '#fff',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  reportTargetChipDark: { borderColor: '#2a2a33', backgroundColor: '#1c1c22' },
  reportTargetChipActive: { borderColor: '#111', backgroundColor: '#f2f2f7' },
  reportTargetChipActiveDark: { borderColor: '#fff', backgroundColor: '#2a2a33' },
  reportTargetChipText: { color: '#222', fontWeight: '900' },
  reportTargetChipTextDark: { color: '#d7d7e0' },
  reportTargetChipTextActive: { color: '#111' },
  reportBtnDanger: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#b00020',
    borderWidth: 0,
  },
  reportBtnDangerDark: { backgroundColor: '#cf6679' },
  reportBtnDangerText: { color: '#fff', fontWeight: '800', fontSize: 13 },
  summaryModal: {
    // On desktop web, constrain width/height so it feels like a modal (not a giant sheet).
    ...(Platform.OS === 'web'
      ? ({ width: '92%', maxWidth: 720, maxHeight: 640, alignSelf: 'center' } as const)
      : ({ width: '88%', maxHeight: '80%' } as const)),
    minHeight: 0,
    // Modals should be white in light mode.
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
  },
  summaryTitle: { fontSize: 18, fontWeight: '700', marginBottom: 10, color: '#111' },
  summaryLoadingRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 8 },
  summaryLoadingText: { color: '#555', fontWeight: '600' },
  // IMPORTANT: allow scroll areas inside modals to shrink on small screens
  // so footer buttons (Done/Close/Cancel) remain reachable.
  summaryScroll: {
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
    ...(Platform.OS === 'web' ? ({ width: '100%', alignSelf: 'stretch' } as const) : null),
  },
  summaryText: { color: '#222', lineHeight: 20 },
  summaryButtons: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 12, gap: 10 },
  summaryModalDark: { backgroundColor: '#14141a' },
  summaryTitleDark: { color: '#fff' },
  summaryTextDark: { color: '#d7d7e0' },
  helperInput: {
    minHeight: 44,
    maxHeight: 140,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#ddd',
    backgroundColor: '#fafafa',
    color: '#111',
    ...(Platform.OS === 'web' ? ({ width: '100%', alignSelf: 'stretch' } as const) : null),
  },
  helperInputFollowUp: {
    marginTop: 10,
  },
  helperInputDark: {
    borderColor: '#2a2a33',
    backgroundColor: '#1c1c22',
    color: '#fff',
  },
  helperModeRow: { marginTop: 8 },
  helperModeSegment: {
    flexDirection: 'row',
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: '#e9e9ee',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#ddd',
  },
  helperModeSegmentDark: {
    backgroundColor: '#1c1c22',
    borderColor: '#2a2a33',
  },
  helperModeBtn: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  helperModeBtnActive: {
    backgroundColor: '#111',
  },
  helperModeBtnActiveDark: {
    backgroundColor: '#ffffff',
  },
  helperModeBtnText: { fontWeight: '800', color: '#111' },
  helperModeBtnTextDark: { color: '#fff' },
  helperModeBtnTextActive: { color: '#fff' },
  helperModeBtnTextActiveDark: { color: '#111' },
  helperHint: { marginTop: 8, fontSize: 12, color: '#666', fontWeight: '600' },
  helperHintDark: { color: '#a7a7b4' },
  helperBlock: { marginTop: 10 },
  helperSectionTitle: { fontSize: 13, fontWeight: '800', marginBottom: 6, color: '#111' },
  helperTurnBubble: {
    borderRadius: 12,
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e1e1e6',
  },
  helperTurnBubbleUser: {
    backgroundColor: '#f7f7fb',
  },
  helperTurnBubbleAssistant: {
    backgroundColor: '#f0f0f5',
  },
  helperTurnBubbleDark: {
    borderColor: '#2a2a33',
  },
  helperTurnBubbleUserDark: {
    backgroundColor: '#1c1c22',
  },
  helperTurnBubbleAssistantDark: {
    backgroundColor: '#14141a',
  },
  helperTurnLabel: {
    fontSize: 12,
    fontWeight: '800',
    opacity: 0.8,
    marginBottom: 6,
  },
  helperSuggestionBubble: {
    borderRadius: 12,
    padding: 12,
    backgroundColor: '#f4f4f4',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e7e7ea',
  },
  helperSuggestionBubbleDark: {
    backgroundColor: '#1c1c22',
    borderColor: '#2a2a33',
  },
  helperSuggestionText: { color: '#222', lineHeight: 20 },
  helperSuggestionActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 10 },
  actionMenuOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.35)' },
  actionMenuCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    overflow: 'hidden',
    ...(Platform.OS === 'web'
      ? { boxShadow: '0px 10px 18px rgba(0,0,0,0.22)' }
      : { shadowColor: '#000', shadowOpacity: 0.22, shadowRadius: 18, shadowOffset: { width: 0, height: 10 } }),
    elevation: 12,
  },
  actionMenuCardDark: { backgroundColor: '#14141a' },
  actionMenuPreviewRow: { padding: 14, borderBottomWidth: 1, borderBottomColor: '#eee' },
  actionMenuPreviewRowDark: { borderBottomColor: '#2a2a33' },
  actionMenuMediaPreview: { gap: 10 },
  actionMenuMediaThumbWrap: { alignSelf: 'flex-start' },
  actionMenuMediaThumb: { width: 96, height: 96, borderRadius: 12 },
  actionMenuMediaThumbPlaceholder: {
    width: 96,
    height: 96,
    borderRadius: 12,
    backgroundColor: '#e9e9ee',
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionMenuMediaThumbPlaceholderText: { color: '#555', fontWeight: '700' },
  actionMenuMediaMeta: { color: '#666', fontWeight: '700', fontSize: 12, marginTop: -4 },
  actionMenuMediaMetaDark: { color: '#a7a7b4' },
  actionMenuMediaCaption: { color: '#222', lineHeight: 18 },
  actionMenuMediaCaptionDark: { color: '#d7d7e0' },
  actionMenuOptions: { paddingVertical: 6 },
  actionMenuOptionsScroll: {
    flexGrow: 0,
    flexShrink: 1,
    minHeight: 0,
  },
  actionMenuOptionsContent: { paddingVertical: 6 },
  reactionInfoRow: { flexDirection: 'row', alignItems: 'baseline', flexWrap: 'wrap' },
  reactionInfoRemoveHint: { opacity: 0.75, fontSize: 12, fontWeight: '700', fontStyle: 'italic', marginLeft: 8 },
  reactionOverlay: {
    position: 'absolute',
    bottom: -12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0,
  },
  // Always anchor reaction chips to the right edge (incoming + outgoing),
  // so they line up consistently with the sender-side layout.
  reactionOverlayIncoming: { right: 10 },
  reactionOverlayOutgoing: { right: 10, flexDirection: 'row-reverse' },
  mediaHeaderTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  mediaHeaderTopLeft: { flex: 1, paddingRight: 10 },
  mediaHeaderTopRight: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end' },
  mediaHeaderCaptionRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  mediaHeaderCaptionFlex: { flex: 1, marginTop: 0 },
  mediaHeaderCaptionIndicators: { flexDirection: 'row', alignItems: 'flex-end', marginLeft: 10, gap: 6 },
  reactionMiniChip: {
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 3,
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
    ...(Platform.OS === 'web'
      ? { boxShadow: '0px 2px 6px rgba(0,0,0,0.08)' }
      : { shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 6, shadowOffset: { width: 0, height: 2 } }),
    elevation: 2,
  },
  // Keep reaction chips consistent: no overlapping/stacking.
  reactionMiniChipStacked: {
    marginLeft: 0,
  },
  reactionMiniChipDark: {
    backgroundColor: '#1c1c22',
    borderColor: '#2a2a33',
    ...(Platform.OS === 'web' ? { boxShadow: 'none' } : { shadowOpacity: 0 }),
    elevation: 0,
  },
  reactionMiniChipMine: {
    // Higher-contrast "selected by me" in light theme
    backgroundColor: 'rgba(17,17,17,0.18)',
    borderColor: 'rgba(17,17,17,0.65)',
  },
  reactionMiniChipMineDark: {
    backgroundColor: 'rgba(25,118,210,0.22)',
    borderColor: 'rgba(25,118,210,0.45)',
  },
  reactionMiniText: { color: '#111', fontWeight: '800', fontSize: 12 },
  reactionMiniTextDark: { color: '#fff' },
  reactionQuickRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingBottom: 10,
    paddingTop: 6,
    gap: 10,
  },
  reactionQuickScrollContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingRight: 6,
  },
  reactionQuickBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
  },
  reactionQuickBtnDark: {
    backgroundColor: '#1c1c22',
    borderColor: '#2a2a33',
  },
  reactionQuickBtnMine: {
    backgroundColor: 'rgba(17,17,17,0.20)',
    borderColor: 'rgba(17,17,17,0.70)',
  },
  reactionQuickBtnMineDark: {
    backgroundColor: 'rgba(25,118,210,0.25)',
    borderColor: 'rgba(25,118,210,0.45)',
  },
  reactionQuickEmoji: { fontSize: 18 },
  reactionQuickMore: {
    height: 38,
    paddingHorizontal: 12,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
  },
  reactionQuickMoreDark: {
    backgroundColor: '#1c1c22',
    borderColor: '#2a2a33',
  },
  reactionQuickMoreText: { color: '#111', fontWeight: '800' },
  reactionQuickMoreTextDark: { color: '#fff' },
  reactionPickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingVertical: 10,
  },
  reactionPickerBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f2f2f7',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e3e3e3',
  },
  reactionPickerBtnDark: {
    backgroundColor: '#1c1c22',
    borderColor: '#2a2a33',
  },
  reactionPickerBtnMine: {
    backgroundColor: 'rgba(17,17,17,0.20)',
    borderColor: 'rgba(17,17,17,0.70)',
  },
  reactionPickerBtnMineDark: {
    backgroundColor: 'rgba(25,118,210,0.25)',
    borderColor: 'rgba(25,118,210,0.45)',
  },
  reactionPickerEmoji: { fontSize: 20 },
  actionMenuRow: { paddingHorizontal: 16, paddingVertical: 12 },
  actionMenuRowPressed: { opacity: 0.75 },
  actionMenuText: { fontSize: 16, color: '#111', fontWeight: '600' },
  actionMenuTextDark: { color: '#fff' },
  viewerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  viewerCard: {
    width: '100%',
    height: '100%',
    borderRadius: 0,
    overflow: 'hidden',
    backgroundColor: '#000',
    position: 'relative',
  },
  viewerTopBar: {
    height: 52,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(0,0,0,0.35)',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  viewerTitle: { color: '#fff', fontWeight: '700', flex: 1, marginRight: 12 },
  viewerCloseBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  viewerCloseText: { color: '#fff', fontWeight: '700' },
  viewerBody: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  viewerTapArea: { flex: 1, width: '100%', height: '100%' },
  viewerNavBtn: {
    position: 'absolute',
    top: '50%',
    marginTop: -24,
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.18)',
    zIndex: 11,
  },
  viewerNavLeft: { left: 12 },
  viewerNavRight: { right: 12 },
  viewerNavText: { color: '#fff', fontWeight: '900', fontSize: 28, lineHeight: 28, marginTop: -2 },
  // RN-web deprecates `style.resizeMode`; use the Image prop instead.
  viewerImage: { width: '100%', height: '100%' },
  viewerVideo: { width: '100%', height: '100%' },
  viewerFallback: { color: '#fff' },
  toastWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toast: {
    maxWidth: 340,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#111',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  toastDark: {
    backgroundColor: '#1c1c22',
    borderColor: '#2a2a33',
  },
  toastError: {
    backgroundColor: '#b00020',
    borderColor: 'rgba(255,255,255,0.18)',
  },
  toastErrorDark: {
    backgroundColor: '#7f0015',
    borderColor: 'rgba(255,255,255,0.12)',
  },
  toastText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 13,
    textAlign: 'center',
  },
});

export type ChatScreenStyles = typeof styles;
