type AnyRecord = Record<string, any>;

export function buildChatScreenRenderProps(args: AnyRecord): {
  mainProps: AnyRecord;
  overlaysProps: AnyRecord;
} {
  return {
    mainProps: {
      styles: args.styles,
      isDark: args.isDark,
      isWideChatLayout: args.isWideChatLayout,
      header: {
        headerTop: args.headerTop,
        headerTitle: args.headerTitle,
        onPressSummarize: () => args.aiConsentGate.request('summary', args.runAiAction),
        onPressAiHelper: () => args.aiConsentGate.request('helper', args.runAiAction),
        displayName: args.displayName,
        myUserId: args.myUserId,
        avatarProfileBySub: args.avatarProfileBySub,
        avatarUrlByPath: args.avatarUrlByPath,
        isConnecting: args.isConnecting,
        isConnected: args.isConnected,
        isEncryptedChat: args.isEncryptedChat,
        isChannel: args.isChannel,
        dmSettingsOpen: args.dmSettingsOpen,
        setDmSettingsOpen: args.setDmSettingsOpen,
        channelSettingsOpen: args.channelSettingsOpen,
        setChannelSettingsOpen: args.setChannelSettingsOpen,
        dmSettingsCompact: !!args.dmSettingsCompact,
        isDm: args.isDm,
        isGroup: args.isGroup,
        myPrivateKeyReady: !!args.myPrivateKey,
        autoDecrypt: args.autoDecrypt,
        setAutoDecrypt: args.setAutoDecrypt,
        ttlLabel: args.TTL_OPTIONS?.[args.ttlIdx]?.label ?? 'Off',
        onOpenTtlPicker: () => {
          args.setTtlIdxDraft(args.ttlIdx);
          args.setTtlPickerOpen(true);
        },
        sendReadReceipts: args.sendReadReceipts,
        onToggleReadReceipts: (v: unknown) => args.onToggleReadReceipts(!!v),
        groupMembersCountLabel: `${args.groupMembersActiveCount || 0}`,
        groupActionBusy: !!args.groupActionBusy,
        groupMeIsAdmin: !!args.groupMeta?.meIsAdmin,
        onOpenGroupMembers: () => args.setGroupMembersOpen(true),
        onOpenGroupName: () => {
          args.setGroupNameDraft(args.groupMeta?.groupName || '');
          args.setGroupNameEditOpen(true);
        },
        onLeaveGroup: () => void args.groupLeave(),
        channelBusy: !!args.channelActionBusy,
        channelMeIsAdmin: !!args.channelMeta?.meIsAdmin,
        channelIsPublic: !!args.channelMeta?.isPublic,
        channelHasPassword: !!args.channelMeta?.hasPassword,
        channelMembersCountLabel: args.channelMembersCountLabel,
        onOpenChannelMembers: () => args.setChannelMembersOpen(true),
        onOpenChannelAbout: () => {
          args.setChannelAboutDraft(String(args.channelMeta?.aboutText || ''));
          args.setChannelAboutEdit(true);
          args.setChannelAboutOpen(true);
        },
        onOpenChannelName: () => {
          args.setChannelNameDraft(args.channelMeta?.name || '');
          args.setChannelNameEditOpen(true);
        },
        onLeaveChannel: () => void args.channelLeave(),
        channelOnTogglePublic: args.channelSettingsPanelActions?.onTogglePublic,
        channelOnPressPassword: args.channelSettingsPanelActions?.onPressPassword,
        error: args.error,
      },
      body: { resolvedChatBg: args.resolvedChatBg as any },
      list: {
        API_URL: args.API_URL,
        isGroup: args.isGroup,
        groupStatus: args.groupMeta?.meStatus,
        visibleMessagesCount: args.visibleMessages?.length,
        messageListData: args.messageListData as any,
        webPinned: args.webPinned,
        listRef: args.webPinned?.listRef,
        historyHasMore: args.historyHasMore,
        historyLoading: args.historyLoading,
        loadOlderHistory: args.loadOlderHistory,
        renderItem: ({ item, index }: { item: any; index: number }) =>
          args.renderChatListItem({
            styles: args.styles,
            item,
            index,
            messageListData: args.messageListData,
            visibleMessages: args.visibleMessages,
            isDark: args.isDark,
            isDm: args.isDm,
            isGroup: args.isGroup,
            isEncryptedChat: args.isEncryptedChat,
            myUserId: args.myUserId,
            myPublicKey: args.myPublicKey,
            displayName: args.displayName,
            nameBySub: args.nameBySub,
            avatarProfileBySub: args.avatarProfileBySub,
            avatarUrlByPath: args.avatarUrlByPath,
            peerSeenAtByCreatedAt: args.peerSeenAtByCreatedAt,
            getSeenLabelFor: args.getSeenLabelFor,
            normalizeUser: args.normalizeUser,
            nowSec: args.nowSec,
            formatRemaining: args.formatRemaining,
            mediaUrlByPath: args.mediaUrlByPath,
            dmThumbUriByPath: args.dmThumbUriByPath,
            imageAspectByPath: args.imageAspectByPath,
            EMPTY_URI_BY_PATH: args.EMPTY_URI_BY_PATH,
            AVATAR_GUTTER: args.AVATAR_GUTTER,
            chatViewportWidth: args.chatViewportWidth,
            getCappedMediaSize: args.getCappedMediaSize,
            inlineEditTargetId: args.inlineEditTargetId,
            inlineEditDraft: args.inlineEditDraft,
            setInlineEditDraft: args.setInlineEditDraft,
            inlineEditUploading: args.inlineEditUploading,
            inlineEditAttachmentMode: args.inlineEditAttachmentMode,
            pendingMedia: args.pendingMedia,
            commitInlineEdit: args.commitInlineEdit,
            cancelInlineEdit: args.cancelInlineEdit,
            openReactionInfo: args.openReactionInfo,
            sendReaction: args.sendReaction,
            openViewer: args.openViewer,
            openDmMediaViewer: args.openDmMediaViewer,
            openGroupMediaViewer: args.openGroupMediaViewer,
            requestOpenLink: args.requestOpenLink,
            onPressMessage: args.onPressMessage,
            openMessageActions: args.openMessageActions,
            latestOutgoingMessageId: args.latestOutgoingMessageId,
            retryFailedMessage: args.retryFailedMessage,
          }),
      },
      composer: {
        isDm: args.isDm,
        isGroup: args.isGroup,
        isEncryptedChat: args.isEncryptedChat,
        groupMeta: args.groupMeta,
        inlineEditTargetId: args.inlineEditTargetId,
        inlineEditUploading: args.inlineEditUploading,
        cancelInlineEdit: args.cancelInlineEdit,
        pendingMedia: args.pendingMedia,
        setPendingMedia: args.setPendingMediaItems,
        isUploading: args.isUploading,
        replyTarget: args.replyTarget,
        setReplyTarget: args.setReplyTarget,
        messages: args.messages,
        openViewer: args.openViewer,
        typingIndicatorText: args.typingIndicatorText,
        TypingIndicator: args.TypingIndicator,
        typingColor: args.isDark ? args.styles?.typingTextDark?.color : args.styles?.typingText?.color,
        mentionSuggestions: args.mentionSuggestions,
        insertMention: args.insertMention,
        composerSafeAreaStyle: args.composerSafeAreaStyle,
        composerHorizontalInsetsStyle: args.composerHorizontalInsetsStyle,
        textInputRef: args.textInputRef,
        inputEpoch: args.inputEpoch,
        input: args.input,
        onChangeInput: args.onChangeInput,
        isTypingRef: args.isTypingRef,
        sendTyping: args.sendTyping,
        sendMessage: args.sendMessage,
        handlePickMedia: args.handlePickMedia,
      },
    },
    overlaysProps: {
      isDark: args.isDark,
      styles: args.styles,
      insets: { top: args.insets?.top, bottom: args.insets?.bottom },
      aiSummary: args.aiSummary as any,
      aiConsentGate: args.aiConsentGate as any,
      runAiAction: args.runAiAction,
      attach: {
        open: args.attachOpen,
        setOpen: args.setAttachOpen,
        pickFromLibrary: args.pickFromLibrary,
        openCamera: args.openCamera,
        pickDocument: args.pickDocument,
      },
      camera: {
        open: args.cameraOpen,
        setOpen: args.setCameraOpen,
        showAlert: args.showAlert,
        onCaptured: args.handleInAppCameraCaptured,
      },
      aiHelper: args.aiHelper as any,
      copyToClipboard: args.copyToClipboard,
      setInput: args.setInput,
      report: args.chatReport as any,
      cdnMedia: args.cdnMedia,
      messageActionMenu: args.messageActionMenu as any,
      myUserId: args.myUserId,
      myPublicKey: args.myPublicKey,
      displayName: args.displayName,
      isDm: args.isDm,
      encryptedPlaceholder: args.ENCRYPTED_PLACEHOLDER,
      normalizeUser: args.normalizeUser,
      mediaUrlByPath: args.mediaUrlByPath,
      dmThumbUriByPath: args.dmThumbUriByPath,
      quickReactions: [...(args.QUICK_REACTIONS || [])],
      blockedSubsSet: args.blockedSubsSet,
      onBlockUserSub: args.onBlockUserSub,
      uiConfirm: args.uiConfirm,
      messageOps: {
        deleteForMe: args.deleteForMe,
        sendDeleteForEveryone: args.sendDelete,
        sendReaction: args.sendReaction,
        openReactionPicker: args.openReactionPicker,
        setCipherText: args.setCipherText,
        setCipherOpen: args.setCipherOpen,
        beginReply: args.beginReply,
        beginInlineEdit: args.beginInlineEdit,
        setInlineEditAttachmentMode: args.setInlineEditAttachmentMode,
        handlePickMedia: args.handlePickMedia,
        clearPendingMedia: args.clearPendingMedia,
        openReportModalForMessage: args.chatReport?.openReportModalForMessage,
      } as any,
      reactionPickerOpen: args.reactionPickerOpen,
      reactionPickerTarget: args.reactionPickerTarget,
      emojis: [...(args.MORE_REACTIONS || [])],
      closeReactionPicker: args.closeReactionPicker,
      cipher: { open: args.cipherOpen, text: args.cipherText, setOpen: args.setCipherOpen, setText: args.setCipherText },
      reactionInfo: args.reactionInfo as any,
      nameBySub: args.nameBySub,
      info: { infoOpen: args.infoOpen, infoTitle: args.infoTitle, infoBody: args.infoBody, setInfoOpen: args.setInfoOpen },
      ttl: {
        ttlPickerOpen: args.ttlPickerOpen,
        TTL_OPTIONS: args.TTL_OPTIONS,
        ttlIdx: args.ttlIdx,
        ttlIdxDraft: args.ttlIdxDraft,
        setTtlIdxDraft: args.setTtlIdxDraft,
        setTtlPickerOpen: args.setTtlPickerOpen,
        setTtlIdx: args.setTtlIdx,
      },
      groupNameEditOpen: args.groupNameEditOpen,
      groupActionBusy: args.groupActionBusy,
      groupNameDraft: args.groupNameDraft,
      setGroupNameDraft: args.setGroupNameDraft,
      groupNameModalActions: args.groupNameModalActions as any,
      groupMembersOpen: args.groupMembersOpen,
      groupMeta: args.groupMeta as any,
      groupAddMembersDraft: args.groupAddMembersDraft,
      setGroupAddMembersDraft: args.setGroupAddMembersDraft,
      groupMembersModalActions: args.groupMembersModalActions as any,
      groupAddMembersInputRef: args.groupAddMembersInputRef,
      groupMembersVisible: args.groupMembersVisible as any,
      kickCooldownUntilBySub: args.kickCooldownUntilBySub,
      avatarUrlByPath: args.avatarUrlByPath,
      groupKick: args.groupKick,
      groupUpdate: args.groupUpdate,
      channelMembersOpen: args.channelMembersOpen,
      channelMembersVisible: args.channelMembersVisible as any,
      channelMeta: args.channelMeta as any,
      channelActionBusy: args.channelActionBusy,
      channelMembersModalActions: args.channelMembersModalActions as any,
      channelUpdate: args.channelUpdate,
      channelKick: args.channelKick,
      channelAboutOpen: args.channelAboutOpen,
      channelAboutEdit: args.channelAboutEdit,
      channelAboutDraft: args.channelAboutDraft,
      setChannelAboutDraft: args.setChannelAboutDraft,
      setChannelAboutEdit: args.setChannelAboutEdit,
      channelAboutModalActions: args.channelAboutModalActions as any,
      requestOpenLink: args.requestOpenLink,
      channelNameEditOpen: args.channelNameEditOpen,
      channelNameDraft: args.channelNameDraft,
      setChannelNameDraft: args.setChannelNameDraft,
      channelNameModalActions: args.channelNameModalActions as any,
      channelPasswordEditOpen: args.channelPasswordEditOpen,
      channelPasswordDraft: args.channelPasswordDraft,
      setChannelPasswordDraft: args.setChannelPasswordDraft,
      channelPasswordModalActions: args.channelPasswordModalActions as any,
      viewer: args.viewer as any,
      dmFileUriByPath: args.dmFileUriByPath,
      confirmLinkModal: args.confirmLinkModal,
      toast: args.toast,
      toastAnim: args.toastAnim as any,
    },
  };
}

